import type { Config } from "tailwindcss";
import tailwindcssAnimate from "tailwindcss-animate";

const config: Config = {
  darkMode: ["class"],
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        chart: {
          "1": "hsl(var(--chart-1))",
          "2": "hsl(var(--chart-2))",
          "3": "hsl(var(--chart-3))",
          "4": "hsl(var(--chart-4))",
          "5": "hsl(var(--chart-5))",
          "income": "hsl(var(--chart-income))",
          "expense": "hsl(var(--chart-expense))",
          "axis": "hsl(var(--chart-axis))",
          "grid": "hsl(var(--chart-grid))",
          "tooltip-bg": "hsl(var(--chart-tooltip-bg))",
          "tooltip-border": "hsl(var(--chart-tooltip-border))",
          "tooltip-text": "hsl(var(--chart-tooltip-text))",
        },
        marker: {
          "venue": "hsl(var(--marker-venue))",
          "asset": "hsl(var(--marker-asset))",
          "person": "hsl(var(--marker-person))",
          "event": "hsl(var(--marker-event))",
          "default": "hsl(var(--marker-default))",
        },
        status: {
          "on-track": "hsl(var(--status-on-track))",
          "at-risk": "hsl(var(--status-at-risk))",
          "delayed": "hsl(var(--status-delayed))",
          "completed": "hsl(var(--status-completed))",
          "blocked": "hsl(var(--status-blocked))",
          "todo": "hsl(var(--status-todo))",
          "in-review": "hsl(var(--status-in-review))",
          "milestone": "hsl(var(--status-milestone))",
          "critical-path": "hsl(var(--status-critical-path))",
          "dependency": "hsl(var(--status-dependency))",
        },
        priority: {
          low: "hsl(var(--priority-low))",
          medium: "hsl(var(--priority-medium))",
          high: "hsl(var(--priority-high))",
          urgent: "hsl(var(--priority-urgent))",
        },
        semantic: {
          success: "hsl(var(--semantic-success))",
          warning: "hsl(var(--semantic-warning))",
          info: "hsl(var(--semantic-info))",
          accent: "hsl(var(--semantic-accent))",
          purple: "hsl(var(--semantic-purple))",
          cyan: "hsl(var(--semantic-cyan))",
          orange: "hsl(var(--semantic-orange))",
          indigo: "hsl(var(--semantic-indigo))",
        },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      backgroundImage: {
        "gradient-radial": "radial-gradient(var(--tw-gradient-stops))",
        "gradient-conic": "conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
        "fade-in": {
          "0%": { opacity: "0" },
          "100%": { opacity: "1" },
        },
        "slide-up": {
          "0%": { transform: "translateY(10px)", opacity: "0" },
          "100%": { transform: "translateY(0)", opacity: "1" },
        },
        "scale-in": {
          "0%": { opacity: "0", transform: "scale(0.95)" },
          "100%": { opacity: "1", transform: "scale(1)" },
        },
        "slide-in-right": {
          "0%": { transform: "translateX(100%)" },
          "100%": { transform: "translateX(0)" },
        },
        "slide-in-up": {
          "0%": { transform: "translateY(100%)" },
          "100%": { transform: "translateY(0)" },
        },
        "pulse-glow": {
          "0%, 100%": { opacity: "0.4" },
          "50%": { opacity: "1" },
        },
        "scanner-sweep": {
          "0%": { top: "0%" },
          "50%": { top: "100%" },
          "100%": { top: "0%" },
        },
        "progress-fill": {
          "0%": { width: "0%" },
          "100%": { width: "var(--progress-target, 100%)" },
        },
        "collapse-open": {
          from: { height: "0", opacity: "0" },
          to: { height: "var(--radix-collapsible-content-height)", opacity: "1" },
        },
        "collapse-close": {
          from: { height: "var(--radix-collapsible-content-height)", opacity: "1" },
          to: { height: "0", opacity: "0" },
        },
        aurora: {
          "0%": { backgroundPosition: "50% 50%, 50% 50%, 50% 50%" },
          "25%": { backgroundPosition: "50% 50%, 100% 0%, 50% 100%" },
          "50%": { backgroundPosition: "0% 0%, 100% 100%, 0% 0%" },
          "75%": { backgroundPosition: "50% 50%, 0% 100%, 100% 50%" },
          "100%": { backgroundPosition: "50% 50%, 50% 50%, 50% 50%" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "fade-in": "fade-in 0.3s ease-in-out",
        "slide-up": "slide-up 0.4s cubic-bezier(0.16, 1, 0.3, 1)",
        "scale-in": "scale-in 0.2s cubic-bezier(0.25, 0.46, 0.45, 0.94)",
        "slide-in-right": "slide-in-right 0.3s cubic-bezier(0.25, 0.46, 0.45, 0.94)",
        "slide-in-up": "slide-in-up 0.3s cubic-bezier(0.25, 0.46, 0.45, 0.94)",
        "pulse-glow": "pulse-glow 2s ease-in-out infinite",
        "scanner-sweep": "scanner-sweep 2s linear infinite",
        "progress-fill": "progress-fill 1s ease-out forwards",
        "collapse-open": "collapse-open 0.2s ease-out",
        "collapse-close": "collapse-close 0.2s ease-out",
        "aurora": "aurora 30s linear infinite",
      },
      boxShadow: {
        "glow": "var(--shadow-glow)",
        "success-glow": "var(--shadow-success-glow)",
        "success-glow-strong": "var(--shadow-success-glow-strong)",
        "destructive-glow": "var(--shadow-destructive-glow)",
        "destructive-glow-strong": "var(--shadow-destructive-glow-strong)",
        "progress-glow": "var(--shadow-progress-glow)",
        "primary-button": "var(--shadow-primary-button)",
        "primary-button-hover": "var(--shadow-primary-button-hover)",
        "primary-badge": "var(--shadow-primary-badge)",
        "destructive-badge": "var(--shadow-destructive-badge)",
        "glass-button": "var(--shadow-glass-button)",
        "spatial-button": "var(--shadow-spatial-button)",
        "spatial-button-hover": "var(--shadow-spatial-button-hover)",
        "spatial-badge": "var(--shadow-spatial-badge)",
        "input-inset": "var(--shadow-input-inset)",
        "input-focus": "var(--shadow-input-focus)",
        "tab-active": "var(--shadow-tab-active)",
        "aurora-badge": "var(--shadow-aurora-badge)",
        "today-line": "var(--shadow-today-line)",
        "icon-glow": "var(--shadow-icon-glow)",
        "bar-inset": "var(--shadow-bar-inset)",
        "bar-glow": "var(--shadow-bar-glow)",
        "dot-glow": "var(--shadow-dot-glow)",
        "inner-highlight": "var(--shadow-inner-highlight)",
        "inner-highlight-strong": "var(--shadow-inner-highlight-strong)",
        "sticky-column": "var(--shadow-sticky-column)",
        "card-hover": "var(--shadow-card-hover)",
        "card-dramatic": "var(--shadow-card-dramatic)",
        "clock-glow": "var(--shadow-clock-glow)",
        "status-success-glow": "var(--shadow-status-success-glow)",
        "status-warning-glow": "var(--shadow-status-warning-glow)",
        "status-info-glow": "var(--shadow-status-info-glow)",
        "icon-glow-strong": "var(--shadow-icon-glow-strong)",
        "legend-dot": "var(--shadow-legend-dot)",
        "conflict-glow": "var(--shadow-conflict-glow)",
        "field-selected": "var(--shadow-field-selected)",
        "success-glow-medium": "var(--shadow-success-glow-medium)",
        "inner-destructive": "var(--shadow-inner-destructive)",
        "inner-subtle": "var(--shadow-inner-subtle)",
        "nav-active": "var(--shadow-nav-active)",
        "nav-badge": "var(--shadow-nav-badge)",
        "success-ambient": "var(--shadow-success-ambient)",
        "destructive-ambient": "var(--shadow-destructive-ambient)",
        "success-button": "var(--shadow-success-button)",
        "success-node": "var(--shadow-success-node)",
        "spatial": "var(--shadow-spatial)",
        "spatial-hover": "var(--shadow-spatial-hover)",
      },
      zIndex: {
        "behind": "-1",
        "base": "0",
        "raised": "10",
        "sticky": "20",
        "dropdown": "30",
        "navigation": "40",
        "overlay": "50",
        "modal": "60",
        "toast": "70",
        "copilot": "90",
        "max": "100",
      },
      transitionDuration: {
        "instant": "0ms",
        "fast": "150ms",
        "normal": "200ms",
        "moderate": "300ms",
        "slow": "400ms",
        "slower": "500ms",
        "deliberate": "700ms",
      },
      transitionTimingFunction: {
        "decelerate": "cubic-bezier(0.25, 0.46, 0.45, 0.94)",
        "overshoot": "cubic-bezier(0.23, 1, 0.32, 1)",
        "expo": "cubic-bezier(0.16, 1, 0.3, 1)",
      },
    },
  },
  plugins: [tailwindcssAnimate],
};
export default config;
