import { NextRequest, NextResponse } from 'next/server';
import { requirePolicy } from '@/lib/api/guard';
import { badRequest, notFound, supabaseError, serverError } from '@/lib/api/response';
import { captureError } from '@/lib/observability';

/**
 * GET /api/invoices/[id]/receipt
 * Generate and return a payment receipt as downloadable HTML.
 */
export async function GET(
  request: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  const { id } = await params;

  if (!id) {
    return badRequest('Invoice ID is required');
  }

  try {
    const auth = await requirePolicy('entity.read');
    if (auth.error) return auth.error;
    const { supabase } = auth;

    const { data: invoice, error } = await supabase
      .from('invoices')
      .select(`
        id,
        invoice_number,
        status,
        subtotal,
        tax_amount,
        total,
        currency,
        issue_date,
        due_date,
        paid_at,
        notes,
        client:companies(id, name, email),
        organization:organizations(id, name)
      `)
      .eq('id', id)
      .single();

    if (error) return supabaseError(error);
    if (!invoice) return notFound('Invoice');

    const client = Array.isArray(invoice.client) ? invoice.client[0] : invoice.client;
    const org = Array.isArray(invoice.organization) ? invoice.organization[0] : invoice.organization;

    const currencySymbol = invoice.currency === 'USD' ? '$' : invoice.currency === 'EUR' ? '€' : invoice.currency === 'GBP' ? '£' : `${invoice.currency} `;
    const fmt = (amount: number | null) => `${currencySymbol}${(amount || 0).toFixed(2)}`;
    const fmtDate = (d: string | null) => d ? new Date(d).toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' }) : '—';

    const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Receipt – ${invoice.invoice_number}</title>
  <style>
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; max-width: 700px; margin: 40px auto; padding: 0 20px; color: #1a1a1a; }
    .header { display: flex; justify-content: space-between; align-items: flex-start; margin-bottom: 32px; }
    .badge { display: inline-block; padding: 4px 12px; border-radius: 9999px; font-size: 12px; font-weight: 600; text-transform: uppercase; background: #dcfce7; color: #166534; }
    h1 { font-size: 24px; margin: 0 0 4px; }
    .meta { color: #6b7280; font-size: 14px; }
    table { width: 100%; border-collapse: collapse; margin: 24px 0; }
    th, td { text-align: left; padding: 10px 12px; border-bottom: 1px solid #e5e7eb; font-size: 14px; }
    th { font-weight: 600; color: #6b7280; font-size: 12px; text-transform: uppercase; }
    .text-right { text-align: right; }
    .totals td { border-bottom: none; }
    .totals .total-row td { font-weight: 700; font-size: 16px; border-top: 2px solid #1a1a1a; }
    .footer { margin-top: 40px; padding-top: 20px; border-top: 1px solid #e5e7eb; color: #9ca3af; font-size: 12px; text-align: center; }
    @media print { body { margin: 0; } }
  </style>
</head>
<body>
  <div class="header">
    <div>
      <h1>Payment Receipt</h1>
      <p class="meta">${org?.name || 'ATLVS'}</p>
    </div>
    <div style="text-align: right;">
      <span class="badge">Paid</span>
      <p class="meta" style="margin-top: 8px;">${invoice.invoice_number}</p>
    </div>
  </div>

  <table>
    <tr><th>Bill To</th><th>Invoice Date</th><th>Payment Date</th></tr>
    <tr>
      <td>${client?.name || '—'}</td>
      <td>${fmtDate(invoice.issue_date)}</td>
      <td>${fmtDate(invoice.paid_at)}</td>
    </tr>
  </table>

  <table class="totals">
    <tr><td>Subtotal</td><td class="text-right">${fmt(invoice.subtotal)}</td></tr>
    <tr><td>Tax</td><td class="text-right">${fmt(invoice.tax_amount)}</td></tr>
    <tr class="total-row"><td>Total Paid</td><td class="text-right">${fmt(invoice.total)}</td></tr>
  </table>

  ${invoice.notes ? `<p style="margin-top: 24px; font-size: 14px; color: #6b7280;"><strong>Notes:</strong> ${invoice.notes}</p>` : ''}

  <div class="footer">
    <p>This receipt was generated by ${org?.name || 'ATLVS'}. Thank you for your payment.</p>
  </div>
</body>
</html>`;

    return new NextResponse(html, {
      status: 200,
      headers: {
        'Content-Type': 'text/html; charset=utf-8',
        'Content-Disposition': `attachment; filename="receipt-${invoice.invoice_number}.html"`,
      },
    });
  } catch (err) {
    captureError(err, 'api.invoices.id.receipt.error');
    return serverError('Failed to generate receipt');
  }
}
