import {
  LayoutDashboard,
  Calendar,
  CheckSquare,
  GitBranch,
  Package,
  FileText,
  FolderKanban,
  Clapperboard,
  ListMusic,
  Users,
  Box,
  MapPin,
  ClipboardList,
  TrendingUp,
  Filter,
  ShoppingCart,
  Image,
  Shield,
  BarChart3,
  Lightbulb,
  Award,
  MessageSquare,
  Trophy,
  Store,
  Compass,
  Link,
  User,
  Building2,
  CreditCard,
  History,
  BookOpen,
  Cpu,
  LifeBuoy,
  Truck,
  Clock,
  DollarSign,
  Megaphone,
  Bell,
  Mail,
  StickyNote,
  ThumbsUp,
  type LucideIcon,
} from "lucide-react";

export interface NavItem {
  title: string;
  path: string;
  icon: LucideIcon;
  description?: string;
  permission?: string;
  badge?: string;
  subpages?: { title: string; path: string }[];
}

export interface NavSection {
  title: string;
  items: NavItem[];
  defaultExpanded?: boolean;
}

export const sidebarNavigation: NavSection[] = [
  {
    title: "Dashboard",
    defaultExpanded: true,
    items: [
      {
        title: "Dashboard",
        path: "/dashboard",
        icon: LayoutDashboard,
        description: "Overview and key metrics",
        permission: "dashboard.read",
        subpages: [
          { title: "Overview", path: "/dashboard/overview" },
          { title: "Analytics", path: "/dashboard/analytics" },
          { title: "Activity", path: "/dashboard/activity" },
        ],
      },
    ],
  },
  {
    title: "Work",
    defaultExpanded: true,
    items: [
      {
        title: "Calendar",
        path: "/work/calendar",
        icon: Calendar,
        description: "Unified calendar across all modules",
        permission: "calendar.read",
        subpages: [
          { title: "Schedule", path: "/work/calendar/schedule" },
          { title: "Availability", path: "/work/calendar/availability" },
          { title: "Resources", path: "/work/calendar/resources" },
          { title: "Bookings", path: "/work/calendar/bookings" },
        ],
      },
      {
        title: "Tasks",
        path: "/work/tasks",
        icon: CheckSquare,
        description: "Task management across all projects",
        permission: "tasks.read",
        subpages: [
          { title: "My Tasks", path: "/work/tasks/my-tasks" },
          { title: "Assigned", path: "/work/tasks/assigned" },
          { title: "Watching", path: "/work/tasks/watching" },
          { title: "Completed", path: "/work/tasks/completed" },
          { title: "Templates", path: "/work/tasks/templates" },
        ],
      },
      {
        title: "Workflows",
        path: "/work/workflows",
        icon: GitBranch,
        description: "Automation and process management",
        permission: "workflows.read",
        subpages: [
          { title: "Active", path: "/work/workflows/active" },
          { title: "Drafts", path: "/work/workflows/drafts" },
          { title: "Runs", path: "/work/workflows/runs" },
          { title: "Templates", path: "/work/workflows/templates" },
          { title: "Builder", path: "/work/workflows/builder" },
        ],
      },
      {
        title: "Documents",
        path: "/work/documents",
        icon: FileText,
        description: "Document and knowledge management",
        permission: "documents.read",
        subpages: [
          { title: "All", path: "/work/documents/all" },
          { title: "Recent", path: "/work/documents/recent" },
          { title: "Shared", path: "/work/documents/shared" },
          { title: "Templates", path: "/work/documents/templates" },
          { title: "Trash", path: "/work/documents/trash" },
        ],
      },
      {
        title: "Notifications",
        path: "/work/notifications",
        icon: Bell,
        description: "Alerts and notifications",
        permission: "notifications.read",
      },
      {
        title: "Messages",
        path: "/work/messages",
        icon: Mail,
        description: "Team messaging and communication",
        permission: "messages.read",
      },
      {
        title: "Notes",
        path: "/work/notes",
        icon: StickyNote,
        description: "Personal and shared notes",
        permission: "notes.read",
      },
      {
        title: "Approvals",
        path: "/work/approvals",
        icon: ThumbsUp,
        description: "Pending approvals and reviews",
        permission: "approvals.read",
      },
    ],
  },
  {
    title: "Projects",
    defaultExpanded: true,
    items: [
      {
        title: "Productions",
        path: "/projects/productions",
        icon: Clapperboard,
        description: "Event and production management",
        permission: "productions.read",
        subpages: [
          { title: "Active", path: "/projects/productions/active" },
          { title: "Planning", path: "/projects/productions/planning" },
          { title: "Completed", path: "/projects/productions/completed" },
          { title: "Archived", path: "/projects/productions/archived" },
        ],
      },
      {
        title: "Programming",
        path: "/projects/programming",
        icon: ListMusic,
        description: "Schedules, run of show, itineraries",
        permission: "programming.read",
        subpages: [
          { title: "Schedule", path: "/projects/programming/schedule" },
          { title: "Run of Show", path: "/projects/programming/run-of-show" },
          { title: "Runsheets", path: "/projects/programming/runsheets" },
          { title: "Cue Sheets", path: "/projects/programming/cue-sheets" },
          { title: "Setlists", path: "/projects/programming/setlists" },
          { title: "Itineraries", path: "/projects/programming/itineraries" },
          { title: "Rehearsals", path: "/projects/programming/rehearsals" },
        ],
      },
      {
        title: "Places",
        path: "/projects/places",
        icon: MapPin,
        description: "Venue and location management",
        permission: "places.read",
        subpages: [
          { title: "Venues", path: "/projects/places/venues" },
          { title: "Spaces", path: "/projects/places/spaces" },
          { title: "Floor Plans", path: "/projects/places/floor-plans" },
          { title: "Site Surveys", path: "/projects/places/site-surveys" },
          { title: "Stage Plots", path: "/projects/places/stage-plots" },
          { title: "Seating Charts", path: "/projects/places/seating-charts" },
        ],
      },
      {
        title: "Procedures",
        path: "/projects/procedures",
        icon: ClipboardList,
        description: "SOPs and operational procedures",
        permission: "procedures.read",
        subpages: [
          { title: "Active", path: "/projects/procedures/active" },
          { title: "Drafts", path: "/projects/procedures/drafts" },
          { title: "Checklists", path: "/projects/procedures/checklists" },
          { title: "Training", path: "/projects/procedures/training" },
        ],
      },
      {
        title: "Call Sheets",
        path: "/projects/call-sheets",
        icon: FileText,
        description: "Production call sheets",
        permission: "call-sheets.read",
      },
      {
        title: "Riders",
        path: "/projects/riders",
        icon: FileText,
        description: "Technical and hospitality riders",
        permission: "riders.read",
      },
      {
        title: "Templates",
        path: "/projects/templates",
        icon: FolderKanban,
        description: "Project templates",
        permission: "templates.read",
      },
    ],
  },
  {
    title: "People",
    defaultExpanded: false,
    items: [
      {
        title: "Directory",
        path: "/people/directory",
        icon: Users,
        description: "Staff and contact directory",
        permission: "people.read",
      },
      {
        title: "Teams",
        path: "/people/teams",
        icon: Users,
        description: "Team management",
        permission: "teams.read",
      },
      {
        title: "Org Chart",
        path: "/people/org-chart",
        icon: Users,
        description: "Organization structure",
        permission: "org-chart.read",
      },
      {
        title: "Availability",
        path: "/people/availability",
        icon: Calendar,
        description: "Staff availability",
        permission: "availability.read",
      },
      {
        title: "Certifications",
        path: "/people/certifications",
        icon: Award,
        description: "Skills and certifications",
        permission: "certifications.read",
      },
      {
        title: "Contractors",
        path: "/people/contractors",
        icon: Users,
        description: "Contractor management",
        permission: "contractors.read",
      },
      {
        title: "Crew",
        path: "/people/crew",
        icon: Users,
        description: "Crew management",
        permission: "crew.read",
      },
      {
        title: "Crew Calls",
        path: "/people/crew-calls",
        icon: FileText,
        description: "Crew call sheets",
        permission: "crew-calls.read",
      },
      {
        title: "Scheduling",
        path: "/people/scheduling",
        icon: Calendar,
        description: "Crew scheduling",
        permission: "scheduling.read",
      },
      {
        title: "Shifts",
        path: "/people/shifts",
        icon: Clock,
        description: "Shift management",
        permission: "shifts.read",
      },
      {
        title: "Timesheets",
        path: "/people/timesheets",
        icon: Clock,
        description: "Time tracking",
        permission: "timesheets.read",
      },
      {
        title: "Payroll",
        path: "/people/payroll",
        icon: DollarSign,
        description: "Payroll management",
        permission: "payroll.read",
      },
      {
        title: "Talent",
        path: "/people/talent",
        icon: Users,
        description: "Talent management",
        permission: "talent.read",
      },
      {
        title: "Artists",
        path: "/people/artists",
        icon: Users,
        description: "Artist management",
        permission: "artists.read",
      },
    ],
  },
  {
    title: "Business",
    defaultExpanded: false,
    items: [
      {
        title: "Pipeline",
        path: "/business/pipeline",
        icon: Filter,
        description: "Sales and opportunity pipeline",
        permission: "pipeline.read",
        subpages: [
          { title: "Deals", path: "/business/pipeline/deals" },
          { title: "Contacts", path: "/business/pipeline/contacts" },
          { title: "Companies", path: "/business/pipeline/companies" },
          { title: "Activities", path: "/business/pipeline/activities" },
          { title: "Proposals", path: "/business/pipeline/proposals" },
        ],
      },
      {
        title: "Quotes",
        path: "/business/quotes",
        icon: FileText,
        description: "Quote management",
        permission: "quotes.read",
      },
      {
        title: "Contracts",
        path: "/business/contracts",
        icon: FileText,
        description: "Contract management",
        permission: "contracts.read",
      },
      {
        title: "Forecast",
        path: "/business/forecast",
        icon: TrendingUp,
        description: "Financial and resource forecasting",
        permission: "forecast.read",
        subpages: [
          { title: "Revenue", path: "/business/forecast/revenue" },
          { title: "Costs", path: "/business/forecast/costs" },
          { title: "Resources", path: "/business/forecast/resources" },
          { title: "Scenarios", path: "/business/forecast/scenarios" },
        ],
      },
      {
        title: "Budgets",
        path: "/business/budgets",
        icon: DollarSign,
        description: "Budget management",
        permission: "budgets.read",
      },
      {
        title: "Invoices",
        path: "/business/invoices",
        icon: FileText,
        description: "Invoice management",
        permission: "invoices.read",
      },
      {
        title: "Expenses",
        path: "/business/expenses",
        icon: DollarSign,
        description: "Expense tracking",
        permission: "expenses.read",
      },
      {
        title: "Procurement",
        path: "/business/procurement",
        icon: ShoppingCart,
        description: "Purchasing and vendor management",
        permission: "procurement.read",
        subpages: [
          { title: "Requisitions", path: "/business/procurement/requisitions" },
          { title: "Orders", path: "/business/procurement/orders" },
          { title: "Vendors", path: "/business/procurement/vendors" },
          { title: "RFQ", path: "/business/procurement/rfq" },
        ],
      },
      {
        title: "Compliance",
        path: "/business/compliance",
        icon: Shield,
        description: "Compliance and risk management",
        permission: "compliance.read",
        subpages: [
          { title: "Policies", path: "/business/compliance/policies" },
          { title: "Audits", path: "/business/compliance/audits" },
          { title: "Risks", path: "/business/compliance/risks" },
          { title: "Incidents", path: "/business/compliance/incidents" },
        ],
      },
      {
        title: "Reports",
        path: "/business/reports",
        icon: BarChart3,
        description: "Reporting and analytics",
        permission: "reports.read",
        subpages: [
          { title: "Library", path: "/business/reports/library" },
          { title: "Scheduled", path: "/business/reports/scheduled" },
          { title: "Builder", path: "/business/reports/builder" },
          { title: "Exports", path: "/business/reports/exports" },
        ],
      },
      {
        title: "Insights",
        path: "/business/insights",
        icon: Lightbulb,
        description: "AI-powered analytics and recommendations",
        permission: "insights.read",
        subpages: [
          { title: "Trends", path: "/business/insights/trends" },
          { title: "Anomalies", path: "/business/insights/anomalies" },
          { title: "Predictions", path: "/business/insights/predictions" },
          { title: "Recommendations", path: "/business/insights/recommendations" },
        ],
      },
    ],
  },
  {
    title: "Assets",
    defaultExpanded: false,
    items: [
      {
        title: "Inventory",
        path: "/assets/inventory",
        icon: Package,
        description: "Equipment inventory",
        permission: "inventory.read",
      },
      {
        title: "Checked Out",
        path: "/assets/checked-out",
        icon: Package,
        description: "Currently checked out items",
        permission: "assets.read",
      },
      {
        title: "Maintenance",
        path: "/assets/maintenance",
        icon: Package,
        description: "Equipment maintenance",
        permission: "maintenance.read",
      },
      {
        title: "Locations",
        path: "/assets/locations",
        icon: MapPin,
        description: "Storage locations",
        permission: "locations.read",
      },
      {
        title: "Categories",
        path: "/assets/categories",
        icon: Package,
        description: "Asset categories",
        permission: "categories.read",
      },
      {
        title: "Kits",
        path: "/assets/kits",
        icon: Package,
        description: "Equipment kits",
        permission: "kits.read",
      },
      {
        title: "Equipment",
        path: "/assets/equipment",
        icon: Package,
        description: "Equipment tracking",
        permission: "equipment.read",
      },
      {
        title: "Transport",
        path: "/assets/transport",
        icon: Truck,
        description: "Transport and logistics",
        permission: "transport.read",
      },
      {
        title: "Products",
        path: "/assets/products",
        icon: Box,
        description: "Product and service catalog",
        permission: "products.read",
        subpages: [
          { title: "Services", path: "/assets/products/services" },
          { title: "Packages", path: "/assets/products/packages" },
          { title: "Catalog", path: "/assets/products/catalog" },
          { title: "Pricing", path: "/assets/products/pricing" },
        ],
      },
      {
        title: "Merchandise",
        path: "/assets/merchandise",
        icon: Box,
        description: "Merchandise management",
        permission: "merchandise.read",
      },
    ],
  },
  {
    title: "Content",
    defaultExpanded: false,
    items: [
      {
        title: "Media",
        path: "/content/media",
        icon: Image,
        description: "Digital asset management",
        permission: "media.read",
      },
      {
        title: "Brand",
        path: "/content/brand",
        icon: Image,
        description: "Brand assets and guidelines",
        permission: "brand.read",
      },
      {
        title: "Marketing",
        path: "/content/marketing",
        icon: Megaphone,
        description: "Marketing materials",
        permission: "marketing.read",
      },
      {
        title: "Social",
        path: "/content/social",
        icon: MessageSquare,
        description: "Social media management",
        permission: "social.read",
      },
      {
        title: "Campaigns",
        path: "/content/campaigns",
        icon: Megaphone,
        description: "Marketing campaigns",
        permission: "campaigns.read",
      },
      {
        title: "Showcase",
        path: "/content/showcase",
        icon: Award,
        description: "Portfolio and work showcase",
        permission: "showcase.read",
        subpages: [
          { title: "Portfolio", path: "/content/showcase/portfolio" },
          { title: "Case Studies", path: "/content/showcase/case-studies" },
          { title: "Testimonials", path: "/content/showcase/testimonials" },
          { title: "Press", path: "/content/showcase/press" },
        ],
      },
      {
        title: "Approvals",
        path: "/content/approvals",
        icon: ThumbsUp,
        description: "Content approvals",
        permission: "content-approvals.read",
      },
    ],
  },
  {
    title: "Network",
    defaultExpanded: false,
    items: [
      {
        title: "Discussions",
        path: "/network/discussions",
        icon: MessageSquare,
        description: "Community forums and discussions",
        permission: "discussions.read",
        subpages: [
          { title: "All", path: "/network/discussions/all" },
          { title: "My Posts", path: "/network/discussions/my-posts" },
          { title: "Categories", path: "/network/discussions/categories" },
        ],
      },
      {
        title: "Challenges",
        path: "/network/challenges",
        icon: Trophy,
        description: "Competitions and challenges",
        permission: "challenges.read",
        subpages: [
          { title: "Active", path: "/network/challenges/active" },
          { title: "Past", path: "/network/challenges/past" },
          { title: "My Entries", path: "/network/challenges/my-entries" },
          { title: "Leaderboard", path: "/network/challenges/leaderboard" },
        ],
      },
      {
        title: "Marketplace",
        path: "/network/marketplace",
        icon: Store,
        description: "Services and product marketplace",
        permission: "marketplace.read",
        subpages: [
          { title: "Browse", path: "/network/marketplace/browse" },
          { title: "My Listings", path: "/network/marketplace/my-listings" },
          { title: "Bookings", path: "/network/marketplace/bookings" },
          { title: "Reviews", path: "/network/marketplace/reviews" },
        ],
      },
      {
        title: "Opportunities",
        path: "/network/opportunities",
        icon: Compass,
        description: "Job board and opportunities",
        permission: "opportunities.read",
        subpages: [
          { title: "Jobs", path: "/network/opportunities/jobs" },
          { title: "Gigs", path: "/network/opportunities/gigs" },
          { title: "Collaborations", path: "/network/opportunities/collaborations" },
          { title: "My Applications", path: "/network/opportunities/my-applications" },
        ],
      },
      {
        title: "Connections",
        path: "/network/connections",
        icon: Link,
        description: "Professional networking",
        permission: "connections.read",
        subpages: [
          { title: "Network", path: "/network/connections/network" },
          { title: "Requests", path: "/network/connections/requests" },
          { title: "Groups", path: "/network/connections/groups" },
          { title: "Events", path: "/network/connections/events" },
        ],
      },
      {
        title: "Community",
        path: "/network/community",
        icon: Users,
        description: "Community hub",
        permission: "community.read",
      },
    ],
  },
  {
    title: "Account",
    defaultExpanded: false,
    items: [
      {
        title: "Profile",
        path: "/account/profile",
        icon: User,
        description: "Personal profile management",
        permission: "profile.read",
      },
      {
        title: "Organization",
        path: "/account/organization",
        icon: Building2,
        description: "Organization settings",
        permission: "organization.manage",
        subpages: [
          { title: "Settings", path: "/account/organization/settings" },
          { title: "Branding", path: "/account/organization/branding" },
          { title: "Departments", path: "/account/organization/departments" },
          { title: "Roles", path: "/account/organization/roles" },
          { title: "Fields", path: "/account/organization/fields" },
          { title: "Integrations", path: "/account/organization/integrations" },
        ],
      },
      {
        title: "Billing",
        path: "/account/billing",
        icon: CreditCard,
        description: "Subscription and billing management",
        permission: "billing.manage",
        subpages: [
          { title: "Subscription", path: "/account/billing/subscription" },
          { title: "Usage", path: "/account/billing/usage" },
          { title: "Payment Methods", path: "/account/billing/payment-methods" },
          { title: "Invoices", path: "/account/billing/invoices" },
        ],
      },
      {
        title: "History",
        path: "/account/history",
        icon: History,
        description: "Activity and audit history",
        permission: "history.read",
        subpages: [
          { title: "Activity", path: "/account/history/activity" },
          { title: "Logins", path: "/account/history/logins" },
          { title: "Changes", path: "/account/history/changes" },
        ],
      },
      {
        title: "Resources",
        path: "/account/resources",
        icon: BookOpen,
        description: "Help and learning resources",
        permission: "resources.read",
        subpages: [
          { title: "Docs", path: "/account/resources/docs" },
          { title: "Videos", path: "/account/resources/videos" },
          { title: "API", path: "/account/resources/api" },
          { title: "Templates", path: "/account/resources/templates" },
        ],
      },
      {
        title: "Platform",
        path: "/account/platform",
        icon: Cpu,
        description: "Platform configuration",
        permission: "platform.manage",
        subpages: [
          { title: "Features", path: "/account/platform/features" },
          { title: "API Keys", path: "/account/platform/api-keys" },
          { title: "Webhooks", path: "/account/platform/webhooks" },
          { title: "Domains", path: "/account/platform/domains" },
          { title: "Export", path: "/account/platform/export" },
        ],
      },
      {
        title: "Security",
        path: "/account/security",
        icon: Shield,
        description: "Security settings",
        permission: "security.manage",
      },
      {
        title: "Support",
        path: "/account/support",
        icon: LifeBuoy,
        description: "Help and support",
        permission: "support.access",
        subpages: [
          { title: "Tickets", path: "/account/support/tickets" },
          { title: "Knowledge Base", path: "/account/support/knowledge-base" },
          { title: "Status", path: "/account/support/status" },
        ],
      },
    ],
  },
];

export const mobileBottomNav: NavItem[] = [
  { title: "Dashboard", path: "/dashboard", icon: LayoutDashboard },
  { title: "Calendar", path: "/work/calendar", icon: Calendar },
  { title: "Tasks", path: "/work/tasks", icon: CheckSquare },
  { title: "Projects", path: "/projects/productions", icon: Clapperboard },
];
