import type { IntegrationConnector } from "./types";
import { INTEGRATION_CATEGORY, INTEGRATION_TIER, SYNC_DIRECTION } from "@/lib/enums";

export const erpConnectors: IntegrationConnector[] = [
  { id: "netsuite", name: "NetSuite", slug: "netsuite", description: "Oracle NetSuite ERP", category: INTEGRATION_CATEGORY.ERP, tier: INTEGRATION_TIER.ENTERPRISE, logoUrl: "/integrations/netsuite.svg", websiteUrl: "https://www.netsuite.com", docsUrl: "https://docs.oracle.com/en/cloud/saas/netsuite/", auth: { type: "oauth2", oauth2: { authUrl: "https://system.netsuite.com/app/login/oauth2/authorize.nl", tokenUrl: "https://system.netsuite.com/app/login/oauth2/token.nl", scopes: ["restlets", "rest_webservices"] } }, sync: { schedule: "*/15 * * * *", direction: SYNC_DIRECTION.BIDIRECTIONAL, entities: [] }, webhooks: [], fieldMappings: [], features: ["Full GL sync", "Multi-subsidiary"] },
  { id: "sap-b1", name: "SAP Business One", slug: "sap-b1", description: "SAP ERP for SMB", category: INTEGRATION_CATEGORY.ERP, tier: INTEGRATION_TIER.ENTERPRISE, logoUrl: "/integrations/sap.svg", websiteUrl: "https://www.sap.com", docsUrl: "https://help.sap.com", auth: { type: "oauth2", oauth2: { authUrl: "https://accounts.sap.com/oauth2/authorize", tokenUrl: "https://accounts.sap.com/oauth2/token", scopes: [] } }, sync: { schedule: "*/30 * * * *", direction: SYNC_DIRECTION.BIDIRECTIONAL, entities: [] }, webhooks: [], fieldMappings: [], features: ["Manufacturing", "Supply chain"] },
  { id: "dynamics365", name: "Microsoft Dynamics 365", slug: "dynamics365", description: "Unified CRM+ERP", category: INTEGRATION_CATEGORY.ERP, tier: INTEGRATION_TIER.ENTERPRISE, logoUrl: "/integrations/dynamics365.svg", websiteUrl: "https://dynamics.microsoft.com", docsUrl: "https://docs.microsoft.com/dynamics365", auth: { type: "oauth2", oauth2: { authUrl: "https://login.microsoftonline.com/common/oauth2/v2.0/authorize", tokenUrl: "https://login.microsoftonline.com/common/oauth2/v2.0/token", scopes: [] } }, sync: { schedule: "*/15 * * * *", direction: SYNC_DIRECTION.BIDIRECTIONAL, entities: [] }, webhooks: [], fieldMappings: [], features: ["Office 365", "Power Platform"] },
  { id: "sage-intacct", name: "Sage Intacct", slug: "sage-intacct", description: "Cloud financial management", category: INTEGRATION_CATEGORY.ERP, tier: INTEGRATION_TIER.PRO, logoUrl: "/integrations/sage.svg", websiteUrl: "https://www.sage.com", docsUrl: "https://developer.intacct.com", auth: { type: "api_key", apiKey: { headerName: "Authorization", prefix: "Bearer", location: "header" } }, sync: { schedule: "*/30 * * * *", direction: SYNC_DIRECTION.BIDIRECTIONAL, entities: [] }, webhooks: [], fieldMappings: [], features: ["Multi-entity", "Dimensional reporting"] },
  { id: "oracle-fusion", name: "Oracle Fusion Cloud", slug: "oracle-fusion", description: "Enterprise financials", category: INTEGRATION_CATEGORY.ERP, tier: INTEGRATION_TIER.ENTERPRISE, logoUrl: "/integrations/oracle.svg", websiteUrl: "https://www.oracle.com/erp", docsUrl: "https://docs.oracle.com", auth: { type: "oauth2", oauth2: { authUrl: "https://login.oracle.com/oam/oauth2/authorize", tokenUrl: "https://login.oracle.com/oam/oauth2/token", scopes: [] } }, sync: { schedule: "0 */4 * * *", direction: SYNC_DIRECTION.BIDIRECTIONAL, entities: [] }, webhooks: [], fieldMappings: [], features: ["Enterprise scale", "AI insights"] },
  { id: "acumatica", name: "Acumatica", slug: "acumatica", description: "Cloud ERP", category: INTEGRATION_CATEGORY.ERP, tier: INTEGRATION_TIER.PRO, logoUrl: "/integrations/acumatica.svg", websiteUrl: "https://www.acumatica.com", docsUrl: "https://help.acumatica.com", auth: { type: "oauth2", oauth2: { authUrl: "{instance}/identity/connect/authorize", tokenUrl: "{instance}/identity/connect/token", scopes: ["api"] } }, sync: { schedule: "*/30 * * * *", direction: SYNC_DIRECTION.BIDIRECTIONAL, entities: [] }, webhooks: [], fieldMappings: [], features: ["Project accounting", "Unlimited users"] },
  { id: "epicor", name: "Epicor", slug: "epicor", description: "Manufacturing ERP", category: INTEGRATION_CATEGORY.ERP, tier: INTEGRATION_TIER.ENTERPRISE, logoUrl: "/integrations/epicor.svg", websiteUrl: "https://www.epicor.com", docsUrl: "https://docs.epicor.com", auth: { type: "api_key", apiKey: { headerName: "Authorization", prefix: "Basic", location: "header" } }, sync: { schedule: "0 */2 * * *", direction: SYNC_DIRECTION.PUSH, entities: [] }, webhooks: [], fieldMappings: [], features: ["Manufacturing", "MES"] },
  { id: "infor", name: "Infor CloudSuite", slug: "infor", description: "Industry-specific ERP", category: INTEGRATION_CATEGORY.ERP, tier: INTEGRATION_TIER.ENTERPRISE, logoUrl: "/integrations/infor.svg", websiteUrl: "https://www.infor.com", docsUrl: "https://docs.infor.com", auth: { type: "oauth2", oauth2: { authUrl: "https://mingle-sso.inforcloudsuite.com/oauth2/authorize", tokenUrl: "https://mingle-sso.inforcloudsuite.com/oauth2/token", scopes: [] } }, sync: { schedule: "0 */4 * * *", direction: SYNC_DIRECTION.BIDIRECTIONAL, entities: [] }, webhooks: [], fieldMappings: [], features: ["Industry-specific", "AI/ML"] },
  { id: "odoo", name: "Odoo", slug: "odoo", description: "Open source ERP", category: INTEGRATION_CATEGORY.ERP, tier: INTEGRATION_TIER.PRO, logoUrl: "/integrations/odoo.svg", websiteUrl: "https://www.odoo.com", docsUrl: "https://www.odoo.com/documentation", auth: { type: "api_key", apiKey: { headerName: "Authorization", prefix: "Bearer", location: "header" } }, sync: { schedule: "*/30 * * * *", direction: SYNC_DIRECTION.BIDIRECTIONAL, entities: [] }, webhooks: [], fieldMappings: [], features: ["Open source", "Modular"] },
  { id: "zoho-books", name: "Zoho Books", slug: "zoho-books", description: "SMB accounting", category: INTEGRATION_CATEGORY.ERP, tier: INTEGRATION_TIER.CORE, logoUrl: "/integrations/zoho.svg", websiteUrl: "https://www.zoho.com/books", docsUrl: "https://www.zoho.com/books/api", auth: { type: "oauth2", oauth2: { authUrl: "https://accounts.zoho.com/oauth/v2/auth", tokenUrl: "https://accounts.zoho.com/oauth/v2/token", scopes: [] } }, sync: { schedule: "0 */1 * * *", direction: SYNC_DIRECTION.PUSH, entities: [] }, webhooks: [], fieldMappings: [], features: ["Affordable", "Multi-currency"] },
];

export const crmConnectors: IntegrationConnector[] = [
  { id: "hubspot", name: "HubSpot", slug: "hubspot", description: "Marketing + Sales + Service", category: INTEGRATION_CATEGORY.CRM, tier: INTEGRATION_TIER.PRO, logoUrl: "/integrations/hubspot.svg", websiteUrl: "https://www.hubspot.com", docsUrl: "https://developers.hubspot.com", auth: { type: "oauth2", oauth2: { authUrl: "https://app.hubspot.com/oauth/authorize", tokenUrl: "https://api.hubapi.com/oauth/v1/token", scopes: ["crm.objects.contacts.read"] } }, sync: { schedule: "*/30 * * * *", direction: SYNC_DIRECTION.BIDIRECTIONAL, entities: [] }, webhooks: [], fieldMappings: [], features: ["Free CRM", "Marketing automation"] },
  { id: "salesforce", name: "Salesforce", slug: "salesforce", description: "Enterprise CRM leader", category: INTEGRATION_CATEGORY.CRM, tier: INTEGRATION_TIER.ENTERPRISE, logoUrl: "/integrations/salesforce.svg", websiteUrl: "https://www.salesforce.com", docsUrl: "https://developer.salesforce.com", auth: { type: "oauth2", oauth2: { authUrl: "https://login.salesforce.com/services/oauth2/authorize", tokenUrl: "https://login.salesforce.com/services/oauth2/token", scopes: ["api"] } }, sync: { schedule: "*/15 * * * *", direction: SYNC_DIRECTION.BIDIRECTIONAL, entities: [] }, webhooks: [], fieldMappings: [], features: ["Enterprise scale", "AppExchange"] },
  { id: "pipedrive", name: "Pipedrive", slug: "pipedrive", description: "Sales pipeline CRM", category: INTEGRATION_CATEGORY.CRM, tier: INTEGRATION_TIER.PRO, logoUrl: "/integrations/pipedrive.svg", websiteUrl: "https://www.pipedrive.com", docsUrl: "https://developers.pipedrive.com", auth: { type: "oauth2", oauth2: { authUrl: "https://oauth.pipedrive.com/oauth/authorize", tokenUrl: "https://oauth.pipedrive.com/oauth/token", scopes: [] } }, sync: { schedule: "*/30 * * * *", direction: SYNC_DIRECTION.BIDIRECTIONAL, entities: [] }, webhooks: [], fieldMappings: [], features: ["Visual pipeline", "Activity tracking"] },
  { id: "zoho-crm", name: "Zoho CRM", slug: "zoho-crm", description: "Full-featured CRM", category: INTEGRATION_CATEGORY.CRM, tier: INTEGRATION_TIER.PRO, logoUrl: "/integrations/zoho.svg", websiteUrl: "https://www.zoho.com/crm", docsUrl: "https://www.zoho.com/crm/developer", auth: { type: "oauth2", oauth2: { authUrl: "https://accounts.zoho.com/oauth/v2/auth", tokenUrl: "https://accounts.zoho.com/oauth/v2/token", scopes: [] } }, sync: { schedule: "*/30 * * * *", direction: SYNC_DIRECTION.BIDIRECTIONAL, entities: [] }, webhooks: [], fieldMappings: [], features: ["Zoho ecosystem", "AI assistant"] },
  { id: "freshsales", name: "Freshsales", slug: "freshsales", description: "AI-powered CRM", category: INTEGRATION_CATEGORY.CRM, tier: INTEGRATION_TIER.PRO, logoUrl: "/integrations/freshsales.svg", websiteUrl: "https://www.freshworks.com/crm", docsUrl: "https://developers.freshworks.com", auth: { type: "api_key", apiKey: { headerName: "Authorization", prefix: "Token", location: "header" } }, sync: { schedule: "*/30 * * * *", direction: SYNC_DIRECTION.BIDIRECTIONAL, entities: [] }, webhooks: [], fieldMappings: [], features: ["Freddy AI", "Built-in phone"] },
  { id: "close", name: "Close", slug: "close", description: "Inside sales CRM", category: INTEGRATION_CATEGORY.CRM, tier: INTEGRATION_TIER.PRO, logoUrl: "/integrations/close.svg", websiteUrl: "https://www.close.com", docsUrl: "https://developer.close.com", auth: { type: "api_key", apiKey: { headerName: "Authorization", prefix: "Basic", location: "header" } }, sync: { schedule: "*/30 * * * *", direction: SYNC_DIRECTION.PUSH, entities: [] }, webhooks: [], fieldMappings: [], features: ["Built-in calling", "Power dialer"] },
  { id: "copper", name: "Copper", slug: "copper", description: "Google Workspace CRM", category: INTEGRATION_CATEGORY.CRM, tier: INTEGRATION_TIER.PRO, logoUrl: "/integrations/copper.svg", websiteUrl: "https://www.copper.com", docsUrl: "https://developer.copper.com", auth: { type: "api_key", apiKey: { headerName: "X-PW-AccessToken", location: "header" } }, sync: { schedule: "*/30 * * * *", direction: SYNC_DIRECTION.BIDIRECTIONAL, entities: [] }, webhooks: [], fieldMappings: [], features: ["Google native", "Gmail sidebar"] },
  { id: "monday-crm", name: "Monday Sales CRM", slug: "monday-crm", description: "Work OS CRM", category: INTEGRATION_CATEGORY.CRM, tier: INTEGRATION_TIER.PRO, logoUrl: "/integrations/monday.svg", websiteUrl: "https://monday.com/crm", docsUrl: "https://developer.monday.com", auth: { type: "oauth2", oauth2: { authUrl: "https://auth.monday.com/oauth2/authorize", tokenUrl: "https://auth.monday.com/oauth2/token", scopes: [] } }, sync: { schedule: "*/30 * * * *", direction: SYNC_DIRECTION.BIDIRECTIONAL, entities: [] }, webhooks: [], fieldMappings: [], features: ["Work OS", "Customizable"] },
  { id: "insightly", name: "Insightly", slug: "insightly", description: "CRM + Project management", category: INTEGRATION_CATEGORY.CRM, tier: INTEGRATION_TIER.PRO, logoUrl: "/integrations/insightly.svg", websiteUrl: "https://www.insightly.com", docsUrl: "https://api.insightly.com", auth: { type: "api_key", apiKey: { headerName: "Authorization", prefix: "Basic", location: "header" } }, sync: { schedule: "0 */1 * * *", direction: SYNC_DIRECTION.PUSH, entities: [] }, webhooks: [], fieldMappings: [], features: ["Project management", "AppConnect"] },
];

export const hrisConnectors: IntegrationConnector[] = [
  { id: "rippling", name: "Rippling", slug: "rippling", description: "HR + IT + Finance", category: INTEGRATION_CATEGORY.HRIS, tier: INTEGRATION_TIER.ENTERPRISE, logoUrl: "/integrations/rippling.svg", websiteUrl: "https://www.rippling.com", docsUrl: "https://developer.rippling.com", auth: { type: "oauth2", oauth2: { authUrl: "https://app.rippling.com/oauth/authorize", tokenUrl: "https://app.rippling.com/oauth/token", scopes: [] } }, sync: { schedule: "0 */4 * * *", direction: SYNC_DIRECTION.BIDIRECTIONAL, entities: [] }, webhooks: [], fieldMappings: [], features: ["Unified platform", "Device management"] },
  { id: "workday", name: "Workday", slug: "workday", description: "Enterprise HCM", category: INTEGRATION_CATEGORY.HRIS, tier: INTEGRATION_TIER.ENTERPRISE, logoUrl: "/integrations/workday.svg", websiteUrl: "https://www.workday.com", docsUrl: "https://community.workday.com", auth: { type: "oauth2", oauth2: { authUrl: "{tenant}.workday.com/ccx/oauth2/authorize", tokenUrl: "{tenant}.workday.com/ccx/oauth2/token", scopes: [] } }, sync: { schedule: "0 2 * * *", direction: SYNC_DIRECTION.BIDIRECTIONAL, entities: [] }, webhooks: [], fieldMappings: [], features: ["Enterprise HCM", "Analytics"] },
  { id: "bamboohr", name: "BambooHR", slug: "bamboohr", description: "SMB HR platform", category: INTEGRATION_CATEGORY.HRIS, tier: INTEGRATION_TIER.PRO, logoUrl: "/integrations/bamboohr.svg", websiteUrl: "https://www.bamboohr.com", docsUrl: "https://documentation.bamboohr.com", auth: { type: "api_key", apiKey: { headerName: "Authorization", prefix: "Basic", location: "header" } }, sync: { schedule: "0 */4 * * *", direction: SYNC_DIRECTION.BIDIRECTIONAL, entities: [] }, webhooks: [], fieldMappings: [], features: ["Self-service", "Time tracking"] },
  { id: "adp", name: "ADP Workforce Now", slug: "adp", description: "Payroll + HR", category: INTEGRATION_CATEGORY.HRIS, tier: INTEGRATION_TIER.ENTERPRISE, logoUrl: "/integrations/adp.svg", websiteUrl: "https://www.adp.com", docsUrl: "https://developers.adp.com", auth: { type: "oauth2", oauth2: { authUrl: "https://accounts.adp.com/auth/oauth/v2/authorize", tokenUrl: "https://accounts.adp.com/auth/oauth/v2/token", scopes: [] } }, sync: { schedule: "0 */6 * * *", direction: SYNC_DIRECTION.BIDIRECTIONAL, entities: [] }, webhooks: [], fieldMappings: [], features: ["Payroll", "Tax filing"] },
  { id: "gusto", name: "Gusto", slug: "gusto", description: "Modern payroll", category: INTEGRATION_CATEGORY.HRIS, tier: INTEGRATION_TIER.PRO, logoUrl: "/integrations/gusto.svg", websiteUrl: "https://gusto.com", docsUrl: "https://docs.gusto.com", auth: { type: "oauth2", oauth2: { authUrl: "https://api.gusto.com/oauth/authorize", tokenUrl: "https://api.gusto.com/oauth/token", scopes: [] } }, sync: { schedule: "0 */4 * * *", direction: SYNC_DIRECTION.BIDIRECTIONAL, entities: [] }, webhooks: [], fieldMappings: [], features: ["Full-service payroll", "Benefits"] },
  { id: "paylocity", name: "Paylocity", slug: "paylocity", description: "Payroll + talent", category: INTEGRATION_CATEGORY.HRIS, tier: INTEGRATION_TIER.PRO, logoUrl: "/integrations/paylocity.svg", websiteUrl: "https://www.paylocity.com", docsUrl: "https://developer.paylocity.com", auth: { type: "oauth2", oauth2: { authUrl: "https://api.paylocity.com/IdentityServer/connect/authorize", tokenUrl: "https://api.paylocity.com/IdentityServer/connect/token", scopes: [] } }, sync: { schedule: "0 */4 * * *", direction: SYNC_DIRECTION.BIDIRECTIONAL, entities: [] }, webhooks: [], fieldMappings: [], features: ["Payroll", "Talent management"] },
  { id: "ukg", name: "UKG Pro", slug: "ukg", description: "Workforce management", category: INTEGRATION_CATEGORY.HRIS, tier: INTEGRATION_TIER.ENTERPRISE, logoUrl: "/integrations/ukg.svg", websiteUrl: "https://www.ukg.com", docsUrl: "https://developer.ukg.com", auth: { type: "oauth2", oauth2: { authUrl: "https://service.ultipro.com/oauth/authorize", tokenUrl: "https://service.ultipro.com/oauth/token", scopes: [] } }, sync: { schedule: "0 */6 * * *", direction: SYNC_DIRECTION.BIDIRECTIONAL, entities: [] }, webhooks: [], fieldMappings: [], features: ["Workforce management", "Scheduling"] },
  { id: "namely", name: "Namely", slug: "namely", description: "Mid-market HR", category: INTEGRATION_CATEGORY.HRIS, tier: INTEGRATION_TIER.PRO, logoUrl: "/integrations/namely.svg", websiteUrl: "https://www.namely.com", docsUrl: "https://developers.namely.com", auth: { type: "oauth2", oauth2: { authUrl: "{company}.namely.com/api/v1/oauth2/authorize", tokenUrl: "{company}.namely.com/api/v1/oauth2/token", scopes: [] } }, sync: { schedule: "0 */4 * * *", direction: SYNC_DIRECTION.BIDIRECTIONAL, entities: [] }, webhooks: [], fieldMappings: [], features: ["HR platform", "Payroll"] },
  { id: "paycom", name: "Paycom", slug: "paycom", description: "Single-database HR", category: INTEGRATION_CATEGORY.HRIS, tier: INTEGRATION_TIER.ENTERPRISE, logoUrl: "/integrations/paycom.svg", websiteUrl: "https://www.paycom.com", docsUrl: "https://www.paycom.com/resources", auth: { type: "api_key", apiKey: { headerName: "Authorization", prefix: "Bearer", location: "header" } }, sync: { schedule: "0 */6 * * *", direction: SYNC_DIRECTION.BIDIRECTIONAL, entities: [] }, webhooks: [], fieldMappings: [], features: ["Single database", "Beti payroll"] },
  { id: "personio", name: "Personio", slug: "personio", description: "European HR", category: INTEGRATION_CATEGORY.HRIS, tier: INTEGRATION_TIER.PRO, logoUrl: "/integrations/personio.svg", websiteUrl: "https://www.personio.com", docsUrl: "https://developer.personio.de", auth: { type: "oauth2", oauth2: { authUrl: "https://api.personio.de/v1/auth", tokenUrl: "https://api.personio.de/v1/auth", scopes: [] } }, sync: { schedule: "0 */4 * * *", direction: SYNC_DIRECTION.BIDIRECTIONAL, entities: [] }, webhooks: [], fieldMappings: [], features: ["European compliance", "Recruiting"] },
];

export const finopsConnectors: IntegrationConnector[] = [
  { id: "stripe", name: "Stripe", slug: "stripe", description: "Payments + subscriptions", category: INTEGRATION_CATEGORY.FINOPS, tier: INTEGRATION_TIER.PRO, logoUrl: "/integrations/stripe.svg", websiteUrl: "https://stripe.com", docsUrl: "https://stripe.com/docs/api", auth: { type: "api_key", apiKey: { headerName: "Authorization", prefix: "Bearer", location: "header" } }, sync: { schedule: "*/15 * * * *", direction: SYNC_DIRECTION.BIDIRECTIONAL, entities: [] }, webhooks: [], fieldMappings: [], features: ["Payments", "Subscriptions", "Invoicing"] },
  { id: "ramp", name: "Ramp", slug: "ramp", description: "Corporate cards + expense", category: INTEGRATION_CATEGORY.FINOPS, tier: INTEGRATION_TIER.PRO, logoUrl: "/integrations/ramp.svg", websiteUrl: "https://ramp.com", docsUrl: "https://docs.ramp.com", auth: { type: "api_key", apiKey: { headerName: "Authorization", prefix: "Bearer", location: "header" } }, sync: { schedule: "*/30 * * * *", direction: SYNC_DIRECTION.PULL, entities: [] }, webhooks: [], fieldMappings: [], features: ["Corporate cards", "Expense management"] },
  { id: "brex", name: "Brex", slug: "brex", description: "Corporate cards + spend", category: INTEGRATION_CATEGORY.FINOPS, tier: INTEGRATION_TIER.PRO, logoUrl: "/integrations/brex.svg", websiteUrl: "https://www.brex.com", docsUrl: "https://developer.brex.com", auth: { type: "oauth2", oauth2: { authUrl: "https://accounts.brex.com/oauth2/v1/authorize", tokenUrl: "https://accounts.brex.com/oauth2/v1/token", scopes: [] } }, sync: { schedule: "*/30 * * * *", direction: SYNC_DIRECTION.PULL, entities: [] }, webhooks: [], fieldMappings: [], features: ["Corporate cards", "Spend management"] },
  { id: "bill", name: "Bill.com", slug: "bill", description: "AP/AR automation", category: INTEGRATION_CATEGORY.FINOPS, tier: INTEGRATION_TIER.PRO, logoUrl: "/integrations/bill.svg", websiteUrl: "https://www.bill.com", docsUrl: "https://developer.bill.com", auth: { type: "oauth2", oauth2: { authUrl: "https://app.bill.com/oauth/authorize", tokenUrl: "https://app.bill.com/oauth/token", scopes: [] } }, sync: { schedule: "*/30 * * * *", direction: SYNC_DIRECTION.BIDIRECTIONAL, entities: [] }, webhooks: [], fieldMappings: [], features: ["AP automation", "AR automation"] },
  { id: "expensify", name: "Expensify", slug: "expensify", description: "Expense management", category: INTEGRATION_CATEGORY.FINOPS, tier: INTEGRATION_TIER.PRO, logoUrl: "/integrations/expensify.svg", websiteUrl: "https://www.expensify.com", docsUrl: "https://integrations.expensify.com", auth: { type: "api_key", apiKey: { headerName: "partnerUserID", location: "query" } }, sync: { schedule: "0 */1 * * *", direction: SYNC_DIRECTION.PULL, entities: [] }, webhooks: [], fieldMappings: [], features: ["Receipt scanning", "Expense reports"] },
  { id: "airbase", name: "Airbase", slug: "airbase", description: "Spend management", category: INTEGRATION_CATEGORY.FINOPS, tier: INTEGRATION_TIER.PRO, logoUrl: "/integrations/airbase.svg", websiteUrl: "https://www.airbase.com", docsUrl: "https://docs.airbase.com", auth: { type: "api_key", apiKey: { headerName: "Authorization", prefix: "Bearer", location: "header" } }, sync: { schedule: "*/30 * * * *", direction: SYNC_DIRECTION.PULL, entities: [] }, webhooks: [], fieldMappings: [], features: ["Spend management", "AP automation"] },
  { id: "divvy", name: "Divvy", slug: "divvy", description: "Expense + budgeting", category: INTEGRATION_CATEGORY.FINOPS, tier: INTEGRATION_TIER.PRO, logoUrl: "/integrations/divvy.svg", websiteUrl: "https://getdivvy.com", docsUrl: "https://developer.divvy.co", auth: { type: "api_key", apiKey: { headerName: "Authorization", prefix: "Bearer", location: "header" } }, sync: { schedule: "*/30 * * * *", direction: SYNC_DIRECTION.PULL, entities: [] }, webhooks: [], fieldMappings: [], features: ["Free software", "Budgeting"] },
  { id: "tipalti", name: "Tipalti", slug: "tipalti", description: "Global payables", category: INTEGRATION_CATEGORY.FINOPS, tier: INTEGRATION_TIER.ENTERPRISE, logoUrl: "/integrations/tipalti.svg", websiteUrl: "https://tipalti.com", docsUrl: "https://api.tipalti.com", auth: { type: "api_key", apiKey: { headerName: "Authorization", prefix: "Bearer", location: "header" } }, sync: { schedule: "*/30 * * * *", direction: SYNC_DIRECTION.BIDIRECTIONAL, entities: [] }, webhooks: [], fieldMappings: [], features: ["Global payments", "Tax compliance"] },
  { id: "coupa", name: "Coupa", slug: "coupa", description: "Procurement + spend", category: INTEGRATION_CATEGORY.FINOPS, tier: INTEGRATION_TIER.ENTERPRISE, logoUrl: "/integrations/coupa.svg", websiteUrl: "https://www.coupa.com", docsUrl: "https://compass.coupa.com", auth: { type: "oauth2", oauth2: { authUrl: "{instance}.coupahost.com/oauth2/authorize", tokenUrl: "{instance}.coupahost.com/oauth2/token", scopes: [] } }, sync: { schedule: "*/30 * * * *", direction: SYNC_DIRECTION.BIDIRECTIONAL, entities: [] }, webhooks: [], fieldMappings: [], features: ["Procurement", "Invoicing"] },
  { id: "concur", name: "SAP Concur", slug: "concur", description: "Travel + expense", category: INTEGRATION_CATEGORY.FINOPS, tier: INTEGRATION_TIER.ENTERPRISE, logoUrl: "/integrations/concur.svg", websiteUrl: "https://www.concur.com", docsUrl: "https://developer.concur.com", auth: { type: "oauth2", oauth2: { authUrl: "https://us.api.concursolutions.com/oauth2/v0/authorize", tokenUrl: "https://us.api.concursolutions.com/oauth2/v0/token", scopes: [] } }, sync: { schedule: "0 */2 * * *", direction: SYNC_DIRECTION.PULL, entities: [] }, webhooks: [], fieldMappings: [], features: ["Travel booking", "Expense reports"] },
];

export const communicationConnectors: IntegrationConnector[] = [
  { id: "slack", name: "Slack", slug: "slack", description: "Team messaging", category: INTEGRATION_CATEGORY.COMMUNICATION, tier: INTEGRATION_TIER.PRO, logoUrl: "/integrations/slack.svg", websiteUrl: "https://slack.com", docsUrl: "https://api.slack.com", auth: { type: "oauth2", oauth2: { authUrl: "https://slack.com/oauth/v2/authorize", tokenUrl: "https://slack.com/api/oauth.v2.access", scopes: [] } }, sync: { direction: SYNC_DIRECTION.PUSH, entities: [] }, webhooks: [], fieldMappings: [], features: ["Notifications", "Slash commands"] },
  { id: "teams", name: "Microsoft Teams", slug: "teams", description: "Enterprise collaboration", category: INTEGRATION_CATEGORY.COMMUNICATION, tier: INTEGRATION_TIER.PRO, logoUrl: "/integrations/teams.svg", websiteUrl: "https://www.microsoft.com/teams", docsUrl: "https://docs.microsoft.com/graph", auth: { type: "oauth2", oauth2: { authUrl: "https://login.microsoftonline.com/common/oauth2/v2.0/authorize", tokenUrl: "https://login.microsoftonline.com/common/oauth2/v2.0/token", scopes: [] } }, sync: { direction: SYNC_DIRECTION.PUSH, entities: [] }, webhooks: [], fieldMappings: [], features: ["Adaptive cards", "Bots"] },
  { id: "zoom", name: "Zoom", slug: "zoom", description: "Video conferencing", category: INTEGRATION_CATEGORY.COMMUNICATION, tier: INTEGRATION_TIER.PRO, logoUrl: "/integrations/zoom.svg", websiteUrl: "https://zoom.us", docsUrl: "https://developers.zoom.us", auth: { type: "oauth2", oauth2: { authUrl: "https://zoom.us/oauth/authorize", tokenUrl: "https://zoom.us/oauth/token", scopes: [] } }, sync: { direction: SYNC_DIRECTION.PUSH, entities: [] }, webhooks: [], fieldMappings: [], features: ["Meetings", "Webinars"] },
  { id: "google-workspace", name: "Google Workspace", slug: "google-workspace", description: "Email + calendar + drive", category: INTEGRATION_CATEGORY.COMMUNICATION, tier: INTEGRATION_TIER.PRO, logoUrl: "/integrations/google.svg", websiteUrl: "https://workspace.google.com", docsUrl: "https://developers.google.com", auth: { type: "oauth2", oauth2: { authUrl: "https://accounts.google.com/o/oauth2/v2/auth", tokenUrl: "https://oauth2.googleapis.com/token", scopes: [] } }, sync: { schedule: "*/15 * * * *", direction: SYNC_DIRECTION.BIDIRECTIONAL, entities: [] }, webhooks: [], fieldMappings: [], features: ["Email", "Calendar", "Drive"] },
  { id: "twilio", name: "Twilio", slug: "twilio", description: "SMS + voice + WhatsApp", category: INTEGRATION_CATEGORY.COMMUNICATION, tier: INTEGRATION_TIER.PRO, logoUrl: "/integrations/twilio.svg", websiteUrl: "https://www.twilio.com", docsUrl: "https://www.twilio.com/docs", auth: { type: "api_key", apiKey: { headerName: "Authorization", prefix: "Basic", location: "header" } }, sync: { direction: SYNC_DIRECTION.PUSH, entities: [] }, webhooks: [], fieldMappings: [], features: ["SMS", "Voice", "WhatsApp"] },
  { id: "sendgrid", name: "SendGrid", slug: "sendgrid", description: "Transactional email", category: INTEGRATION_CATEGORY.COMMUNICATION, tier: INTEGRATION_TIER.PRO, logoUrl: "/integrations/sendgrid.svg", websiteUrl: "https://sendgrid.com", docsUrl: "https://docs.sendgrid.com", auth: { type: "api_key", apiKey: { headerName: "Authorization", prefix: "Bearer", location: "header" } }, sync: { direction: SYNC_DIRECTION.PUSH, entities: [] }, webhooks: [], fieldMappings: [], features: ["Transactional email", "Marketing"] },
  { id: "discord", name: "Discord", slug: "discord", description: "Community messaging", category: INTEGRATION_CATEGORY.COMMUNICATION, tier: INTEGRATION_TIER.CORE, logoUrl: "/integrations/discord.svg", websiteUrl: "https://discord.com", docsUrl: "https://discord.com/developers", auth: { type: "oauth2", oauth2: { authUrl: "https://discord.com/api/oauth2/authorize", tokenUrl: "https://discord.com/api/oauth2/token", scopes: [] } }, sync: { direction: SYNC_DIRECTION.PUSH, entities: [] }, webhooks: [], fieldMappings: [], features: ["Webhooks", "Bots"] },
  { id: "intercom", name: "Intercom", slug: "intercom", description: "Customer messaging", category: INTEGRATION_CATEGORY.COMMUNICATION, tier: INTEGRATION_TIER.PRO, logoUrl: "/integrations/intercom.svg", websiteUrl: "https://www.intercom.com", docsUrl: "https://developers.intercom.com", auth: { type: "oauth2", oauth2: { authUrl: "https://app.intercom.com/oauth", tokenUrl: "https://api.intercom.io/auth/eagle/token", scopes: [] } }, sync: { schedule: "*/30 * * * *", direction: SYNC_DIRECTION.BIDIRECTIONAL, entities: [] }, webhooks: [], fieldMappings: [], features: ["Live chat", "Chatbots"] },
  { id: "zendesk", name: "Zendesk", slug: "zendesk", description: "Support ticketing", category: INTEGRATION_CATEGORY.COMMUNICATION, tier: INTEGRATION_TIER.PRO, logoUrl: "/integrations/zendesk.svg", websiteUrl: "https://www.zendesk.com", docsUrl: "https://developer.zendesk.com", auth: { type: "oauth2", oauth2: { authUrl: "https://{subdomain}.zendesk.com/oauth/authorizations/new", tokenUrl: "https://{subdomain}.zendesk.com/oauth/tokens", scopes: [] } }, sync: { schedule: "*/30 * * * *", direction: SYNC_DIRECTION.BIDIRECTIONAL, entities: [] }, webhooks: [], fieldMappings: [], features: ["Ticketing", "Help center"] },
  { id: "front", name: "Front", slug: "front", description: "Shared inbox", category: INTEGRATION_CATEGORY.COMMUNICATION, tier: INTEGRATION_TIER.PRO, logoUrl: "/integrations/front.svg", websiteUrl: "https://front.com", docsUrl: "https://dev.frontapp.com", auth: { type: "oauth2", oauth2: { authUrl: "https://app.frontapp.com/oauth/authorize", tokenUrl: "https://app.frontapp.com/oauth/token", scopes: [] } }, sync: { schedule: "*/30 * * * *", direction: SYNC_DIRECTION.BIDIRECTIONAL, entities: [] }, webhooks: [], fieldMappings: [], features: ["Shared inbox", "Collaboration"] },
];

export const calendarConnectors: IntegrationConnector[] = [
  { id: "google-calendar", name: "Google Calendar", slug: "google-calendar", description: "Universal calendar sync", category: INTEGRATION_CATEGORY.CALENDAR, tier: INTEGRATION_TIER.CORE, logoUrl: "/integrations/google.svg", websiteUrl: "https://calendar.google.com", docsUrl: "https://developers.google.com/calendar", auth: { type: "oauth2", oauth2: { authUrl: "https://accounts.google.com/o/oauth2/v2/auth", tokenUrl: "https://oauth2.googleapis.com/token", scopes: ["https://www.googleapis.com/auth/calendar"] } }, sync: { schedule: "*/5 * * * *", direction: SYNC_DIRECTION.BIDIRECTIONAL, entities: [] }, webhooks: [], fieldMappings: [], features: ["Event sync", "Availability"] },
  { id: "outlook-calendar", name: "Microsoft Outlook", slug: "outlook-calendar", description: "Enterprise calendar", category: INTEGRATION_CATEGORY.CALENDAR, tier: INTEGRATION_TIER.PRO, logoUrl: "/integrations/outlook.svg", websiteUrl: "https://outlook.com", docsUrl: "https://docs.microsoft.com/graph", auth: { type: "oauth2", oauth2: { authUrl: "https://login.microsoftonline.com/common/oauth2/v2.0/authorize", tokenUrl: "https://login.microsoftonline.com/common/oauth2/v2.0/token", scopes: ["Calendars.ReadWrite"] } }, sync: { schedule: "*/5 * * * *", direction: SYNC_DIRECTION.BIDIRECTIONAL, entities: [] }, webhooks: [], fieldMappings: [], features: ["Exchange sync", "Teams integration"] },
  { id: "calendly", name: "Calendly", slug: "calendly", description: "Scheduling automation", category: INTEGRATION_CATEGORY.CALENDAR, tier: INTEGRATION_TIER.PRO, logoUrl: "/integrations/calendly.svg", websiteUrl: "https://calendly.com", docsUrl: "https://developer.calendly.com", auth: { type: "oauth2", oauth2: { authUrl: "https://auth.calendly.com/oauth/authorize", tokenUrl: "https://auth.calendly.com/oauth/token", scopes: [] } }, sync: { schedule: "*/15 * * * *", direction: SYNC_DIRECTION.BIDIRECTIONAL, entities: [] }, webhooks: [], fieldMappings: [], features: ["Booking pages", "Round robin"] },
  { id: "cal-com", name: "Cal.com", slug: "cal-com", description: "Open source scheduling", category: INTEGRATION_CATEGORY.CALENDAR, tier: INTEGRATION_TIER.CORE, logoUrl: "/integrations/cal.svg", websiteUrl: "https://cal.com", docsUrl: "https://cal.com/docs", auth: { type: "api_key", apiKey: { headerName: "Authorization", prefix: "Bearer", location: "header" } }, sync: { schedule: "*/15 * * * *", direction: SYNC_DIRECTION.BIDIRECTIONAL, entities: [] }, webhooks: [], fieldMappings: [], features: ["Open source", "Self-hosted"] },
  { id: "acuity", name: "Acuity Scheduling", slug: "acuity", description: "Appointment booking", category: INTEGRATION_CATEGORY.CALENDAR, tier: INTEGRATION_TIER.PRO, logoUrl: "/integrations/acuity.svg", websiteUrl: "https://acuityscheduling.com", docsUrl: "https://developers.acuityscheduling.com", auth: { type: "oauth2", oauth2: { authUrl: "https://acuityscheduling.com/oauth2/authorize", tokenUrl: "https://acuityscheduling.com/oauth2/token", scopes: [] } }, sync: { schedule: "*/15 * * * *", direction: SYNC_DIRECTION.BIDIRECTIONAL, entities: [] }, webhooks: [], fieldMappings: [], features: ["Client booking", "Payments"] },
];

export const storageConnectors: IntegrationConnector[] = [
  { id: "google-drive", name: "Google Drive", slug: "google-drive", description: "Cloud storage", category: INTEGRATION_CATEGORY.STORAGE, tier: INTEGRATION_TIER.PRO, logoUrl: "/integrations/google-drive.svg", websiteUrl: "https://drive.google.com", docsUrl: "https://developers.google.com/drive", auth: { type: "oauth2", oauth2: { authUrl: "https://accounts.google.com/o/oauth2/v2/auth", tokenUrl: "https://oauth2.googleapis.com/token", scopes: ["https://www.googleapis.com/auth/drive"] } }, sync: { schedule: "*/30 * * * *", direction: SYNC_DIRECTION.BIDIRECTIONAL, entities: [] }, webhooks: [], fieldMappings: [], features: ["File sync", "Shared drives"] },
  { id: "dropbox", name: "Dropbox", slug: "dropbox", description: "File sync and sharing", category: INTEGRATION_CATEGORY.STORAGE, tier: INTEGRATION_TIER.PRO, logoUrl: "/integrations/dropbox.svg", websiteUrl: "https://www.dropbox.com", docsUrl: "https://www.dropbox.com/developers", auth: { type: "oauth2", oauth2: { authUrl: "https://www.dropbox.com/oauth2/authorize", tokenUrl: "https://api.dropboxapi.com/oauth2/token", scopes: [] } }, sync: { schedule: "*/30 * * * *", direction: SYNC_DIRECTION.BIDIRECTIONAL, entities: [] }, webhooks: [], fieldMappings: [], features: ["File sync", "Team folders"] },
  { id: "onedrive", name: "OneDrive", slug: "onedrive", description: "Microsoft storage", category: INTEGRATION_CATEGORY.STORAGE, tier: INTEGRATION_TIER.PRO, logoUrl: "/integrations/onedrive.svg", websiteUrl: "https://onedrive.live.com", docsUrl: "https://docs.microsoft.com/onedrive", auth: { type: "oauth2", oauth2: { authUrl: "https://login.microsoftonline.com/common/oauth2/v2.0/authorize", tokenUrl: "https://login.microsoftonline.com/common/oauth2/v2.0/token", scopes: ["Files.ReadWrite.All"] } }, sync: { schedule: "*/30 * * * *", direction: SYNC_DIRECTION.BIDIRECTIONAL, entities: [] }, webhooks: [], fieldMappings: [], features: ["Office integration", "SharePoint"] },
  { id: "box", name: "Box", slug: "box", description: "Enterprise content", category: INTEGRATION_CATEGORY.STORAGE, tier: INTEGRATION_TIER.ENTERPRISE, logoUrl: "/integrations/box.svg", websiteUrl: "https://www.box.com", docsUrl: "https://developer.box.com", auth: { type: "oauth2", oauth2: { authUrl: "https://account.box.com/api/oauth2/authorize", tokenUrl: "https://api.box.com/oauth2/token", scopes: [] } }, sync: { schedule: "*/30 * * * *", direction: SYNC_DIRECTION.BIDIRECTIONAL, entities: [] }, webhooks: [], fieldMappings: [], features: ["Enterprise security", "Workflows"] },
  { id: "aws-s3", name: "AWS S3", slug: "aws-s3", description: "Object storage", category: INTEGRATION_CATEGORY.STORAGE, tier: INTEGRATION_TIER.ENTERPRISE, logoUrl: "/integrations/aws.svg", websiteUrl: "https://aws.amazon.com/s3", docsUrl: "https://docs.aws.amazon.com/s3", auth: { type: "api_key", apiKey: { headerName: "Authorization", location: "header" } }, sync: { direction: SYNC_DIRECTION.PUSH, entities: [] }, webhooks: [], fieldMappings: [], features: ["Scalable", "Versioning"] },
];

export const ticketingConnectors: IntegrationConnector[] = [
  { id: "eventbrite", name: "Eventbrite", slug: "eventbrite", description: "Event ticketing", category: INTEGRATION_CATEGORY.TICKETING, tier: INTEGRATION_TIER.PRO, logoUrl: "/integrations/eventbrite.svg", websiteUrl: "https://www.eventbrite.com", docsUrl: "https://www.eventbrite.com/platform/api", auth: { type: "oauth2", oauth2: { authUrl: "https://www.eventbrite.com/oauth/authorize", tokenUrl: "https://www.eventbrite.com/oauth/token", scopes: [] } }, sync: { schedule: "*/15 * * * *", direction: SYNC_DIRECTION.BIDIRECTIONAL, entities: [] }, webhooks: [], fieldMappings: [], features: ["Event creation", "Attendee sync"] },
  { id: "ticketmaster", name: "Ticketmaster", slug: "ticketmaster", description: "Major venue ticketing", category: INTEGRATION_CATEGORY.TICKETING, tier: INTEGRATION_TIER.ENTERPRISE, logoUrl: "/integrations/ticketmaster.svg", websiteUrl: "https://www.ticketmaster.com", docsUrl: "https://developer.ticketmaster.com", auth: { type: "api_key", apiKey: { headerName: "apikey", location: "query" } }, sync: { schedule: "0 */1 * * *", direction: SYNC_DIRECTION.PULL, entities: [] }, webhooks: [], fieldMappings: [], features: ["Venue data", "Event discovery"] },
  { id: "universe", name: "Universe", slug: "universe", description: "Event platform", category: INTEGRATION_CATEGORY.TICKETING, tier: INTEGRATION_TIER.PRO, logoUrl: "/integrations/universe.svg", websiteUrl: "https://www.universe.com", docsUrl: "https://developers.universe.com", auth: { type: "oauth2", oauth2: { authUrl: "https://www.universe.com/oauth/authorize", tokenUrl: "https://www.universe.com/oauth/token", scopes: [] } }, sync: { schedule: "*/30 * * * *", direction: SYNC_DIRECTION.BIDIRECTIONAL, entities: [] }, webhooks: [], fieldMappings: [], features: ["Ticketing", "Marketing"] },
  { id: "dice", name: "Dice", slug: "dice", description: "Music event ticketing", category: INTEGRATION_CATEGORY.TICKETING, tier: INTEGRATION_TIER.PRO, logoUrl: "/integrations/dice.svg", websiteUrl: "https://dice.fm", docsUrl: "https://dice.fm/partners", auth: { type: "api_key", apiKey: { headerName: "Authorization", prefix: "Bearer", location: "header" } }, sync: { schedule: "*/30 * * * *", direction: SYNC_DIRECTION.BIDIRECTIONAL, entities: [] }, webhooks: [], fieldMappings: [], features: ["Music events", "Fan data"] },
  { id: "ticket-tailor", name: "Ticket Tailor", slug: "ticket-tailor", description: "Simple ticketing", category: INTEGRATION_CATEGORY.TICKETING, tier: INTEGRATION_TIER.PRO, logoUrl: "/integrations/ticket-tailor.svg", websiteUrl: "https://www.tickettailor.com", docsUrl: "https://developers.tickettailor.com", auth: { type: "api_key", apiKey: { headerName: "Authorization", prefix: "Bearer", location: "header" } }, sync: { schedule: "*/30 * * * *", direction: SYNC_DIRECTION.BIDIRECTIONAL, entities: [] }, webhooks: [], fieldMappings: [], features: ["Low fees", "Customizable"] },
];

export const identityConnectors: IntegrationConnector[] = [
  { id: "okta", name: "Okta", slug: "okta", description: "Enterprise identity", category: INTEGRATION_CATEGORY.IDENTITY, tier: INTEGRATION_TIER.ENTERPRISE, logoUrl: "/integrations/okta.svg", websiteUrl: "https://www.okta.com", docsUrl: "https://developer.okta.com", auth: { type: "saml", saml: { entityId: "", acsUrl: "", metadataUrl: "" }, scim: { baseUrl: "", version: "2.0", features: ["users", "groups", "provisioning"] } }, sync: { direction: SYNC_DIRECTION.PULL, entities: [] }, webhooks: [], fieldMappings: [], features: ["SSO", "SCIM provisioning"] },
  { id: "azure-ad", name: "Azure AD", slug: "azure-ad", description: "Microsoft identity", category: INTEGRATION_CATEGORY.IDENTITY, tier: INTEGRATION_TIER.ENTERPRISE, logoUrl: "/integrations/azure.svg", websiteUrl: "https://azure.microsoft.com/services/active-directory", docsUrl: "https://docs.microsoft.com/azure/active-directory", auth: { type: "saml", saml: { entityId: "", acsUrl: "", metadataUrl: "" }, scim: { baseUrl: "", version: "2.0", features: ["users", "groups"] } }, sync: { direction: SYNC_DIRECTION.PULL, entities: [] }, webhooks: [], fieldMappings: [], features: ["SSO", "Conditional access"] },
  { id: "google-workspace-sso", name: "Google Workspace SSO", slug: "google-workspace-sso", description: "Google identity", category: INTEGRATION_CATEGORY.IDENTITY, tier: INTEGRATION_TIER.ENTERPRISE, logoUrl: "/integrations/google.svg", websiteUrl: "https://workspace.google.com", docsUrl: "https://support.google.com/a/answer/60224", auth: { type: "saml", saml: { entityId: "", acsUrl: "", metadataUrl: "" } }, sync: { direction: SYNC_DIRECTION.PULL, entities: [] }, webhooks: [], fieldMappings: [], features: ["SSO", "Directory sync"] },
  { id: "onelogin", name: "OneLogin", slug: "onelogin", description: "Cloud identity", category: INTEGRATION_CATEGORY.IDENTITY, tier: INTEGRATION_TIER.ENTERPRISE, logoUrl: "/integrations/onelogin.svg", websiteUrl: "https://www.onelogin.com", docsUrl: "https://developers.onelogin.com", auth: { type: "saml", saml: { entityId: "", acsUrl: "", metadataUrl: "" }, scim: { baseUrl: "", version: "2.0", features: ["users", "groups"] } }, sync: { direction: SYNC_DIRECTION.PULL, entities: [] }, webhooks: [], fieldMappings: [], features: ["SSO", "MFA"] },
  { id: "auth0", name: "Auth0", slug: "auth0", description: "Developer identity", category: INTEGRATION_CATEGORY.IDENTITY, tier: INTEGRATION_TIER.ENTERPRISE, logoUrl: "/integrations/auth0.svg", websiteUrl: "https://auth0.com", docsUrl: "https://auth0.com/docs", auth: { type: "oauth2", oauth2: { authUrl: "{domain}/authorize", tokenUrl: "{domain}/oauth/token", scopes: ["openid", "profile", "email"] } }, sync: { direction: SYNC_DIRECTION.PULL, entities: [] }, webhooks: [], fieldMappings: [], features: ["Universal login", "Social connections"] },
];

export const projectConnectors: IntegrationConnector[] = [
  { id: "asana", name: "Asana", slug: "asana", description: "Project tracking", category: INTEGRATION_CATEGORY.PROJECT, tier: INTEGRATION_TIER.PRO, logoUrl: "/integrations/asana.svg", websiteUrl: "https://asana.com", docsUrl: "https://developers.asana.com", auth: { type: "oauth2", oauth2: { authUrl: "https://app.asana.com/-/oauth_authorize", tokenUrl: "https://app.asana.com/-/oauth_token", scopes: [] } }, sync: { schedule: "*/30 * * * *", direction: SYNC_DIRECTION.BIDIRECTIONAL, entities: [] }, webhooks: [], fieldMappings: [], features: ["Tasks", "Projects", "Portfolios"] },
  { id: "monday", name: "Monday.com", slug: "monday", description: "Work OS platform", category: INTEGRATION_CATEGORY.PROJECT, tier: INTEGRATION_TIER.PRO, logoUrl: "/integrations/monday.svg", websiteUrl: "https://monday.com", docsUrl: "https://developer.monday.com", auth: { type: "oauth2", oauth2: { authUrl: "https://auth.monday.com/oauth2/authorize", tokenUrl: "https://auth.monday.com/oauth2/token", scopes: [] } }, sync: { schedule: "*/30 * * * *", direction: SYNC_DIRECTION.BIDIRECTIONAL, entities: [] }, webhooks: [], fieldMappings: [], features: ["Boards", "Automations"] },
  { id: "jira", name: "Jira", slug: "jira", description: "Issue tracking", category: INTEGRATION_CATEGORY.PROJECT, tier: INTEGRATION_TIER.PRO, logoUrl: "/integrations/jira.svg", websiteUrl: "https://www.atlassian.com/software/jira", docsUrl: "https://developer.atlassian.com/cloud/jira", auth: { type: "oauth2", oauth2: { authUrl: "https://auth.atlassian.com/authorize", tokenUrl: "https://auth.atlassian.com/oauth/token", scopes: ["read:jira-work", "write:jira-work"] } }, sync: { schedule: "*/30 * * * *", direction: SYNC_DIRECTION.BIDIRECTIONAL, entities: [] }, webhooks: [], fieldMappings: [], features: ["Issues", "Sprints", "Boards"] },
  { id: "clickup", name: "ClickUp", slug: "clickup", description: "All-in-one workspace", category: INTEGRATION_CATEGORY.PROJECT, tier: INTEGRATION_TIER.PRO, logoUrl: "/integrations/clickup.svg", websiteUrl: "https://clickup.com", docsUrl: "https://clickup.com/api", auth: { type: "oauth2", oauth2: { authUrl: "https://app.clickup.com/api", tokenUrl: "https://api.clickup.com/api/v2/oauth/token", scopes: [] } }, sync: { schedule: "*/30 * * * *", direction: SYNC_DIRECTION.BIDIRECTIONAL, entities: [] }, webhooks: [], fieldMappings: [], features: ["Tasks", "Docs", "Goals"] },
  { id: "notion", name: "Notion", slug: "notion", description: "Docs + databases", category: INTEGRATION_CATEGORY.PROJECT, tier: INTEGRATION_TIER.PRO, logoUrl: "/integrations/notion.svg", websiteUrl: "https://www.notion.so", docsUrl: "https://developers.notion.com", auth: { type: "oauth2", oauth2: { authUrl: "https://api.notion.com/v1/oauth/authorize", tokenUrl: "https://api.notion.com/v1/oauth/token", scopes: [] } }, sync: { schedule: "*/30 * * * *", direction: SYNC_DIRECTION.BIDIRECTIONAL, entities: [] }, webhooks: [], fieldMappings: [], features: ["Pages", "Databases"] },
];

export const allConnectors: IntegrationConnector[] = [
  ...erpConnectors,
  ...crmConnectors,
  ...hrisConnectors,
  ...finopsConnectors,
  ...communicationConnectors,
  ...calendarConnectors,
  ...storageConnectors,
  ...ticketingConnectors,
  ...identityConnectors,
  ...projectConnectors,
];

export function getConnectorById(id: string): IntegrationConnector | undefined {
  return allConnectors.find((c) => c.id === id);
}

export function getConnectorsByCategory(category: typeof INTEGRATION_CATEGORY[keyof typeof INTEGRATION_CATEGORY]): IntegrationConnector[] {
  return allConnectors.filter((c) => c.category === category);
}

export function getConnectorsByTier(tier: typeof INTEGRATION_TIER[keyof typeof INTEGRATION_TIER]): IntegrationConnector[] {
  return allConnectors.filter((c) => c.tier === tier);
}
