-- Wire Audit: Create 45 missing tables referenced by frontend schemas
-- Generated by wire-audit remediation

-- ============================================================================
-- PREAMBLE: Ensure organization_id exists on tables that may pre-exist from
-- earlier migrations. CREATE TABLE IF NOT EXISTS will skip creation, but the
-- RLS policies below reference organization_id. This block adds the column
-- to any pre-existing table that lacks it.
-- ============================================================================
DO $$
DECLARE
  _tbl text;
BEGIN
  FOR _tbl IN
    SELECT unnest(ARRAY[
      'automation_rules','bank_connections','budget_phases','budget_templates',
      'challenge_participants','client_portal_access','conversations',
      'credit_notes','crew_gig_ratings','document_templates',
      'expense_approval_policies','labor_rule_sets','meeting_types','pay_stubs',
      'payment_milestones','price_lists','products','project_post_mortems',
      'project_templates','punch_lists','quotes','reactions','receipt_scans',
      'reminder_templates','rfp_responses','shift_swap_requests','time_punches',
      'timer_sessions','user_follows','user_points'
    ])
  LOOP
    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = _tbl) THEN
      IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = 'public' AND table_name = _tbl AND column_name = 'organization_id'
      ) THEN
        EXECUTE format(
          'ALTER TABLE public.%I ADD COLUMN organization_id uuid REFERENCES public.organizations(id) ON DELETE CASCADE',
          _tbl
        );
      END IF;
    END IF;
  END LOOP;
END $$;

-- Also make all CREATE POLICY statements idempotent
-- (DROP IF EXISTS before CREATE to handle re-runs)

CREATE TABLE IF NOT EXISTS public.asset_transfers (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  transfer_number text,
  asset_id uuid,
  from_location_id uuid,
  to_location_id uuid,
  status text,
  requested_by uuid,
  approved_by uuid,
  requested_date date,
  ship_date date,
  received_date date,
  reason text,
  notes text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  deleted_at timestamptz,
  created_by uuid REFERENCES auth.users(id)
);

ALTER TABLE public.asset_transfers ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "org_isolation" ON public.asset_transfers;
CREATE POLICY "org_isolation" ON public.asset_transfers
  FOR ALL USING (organization_id = (SELECT organization_id FROM public.organization_members WHERE user_id = auth.uid() LIMIT 1));

CREATE TABLE IF NOT EXISTS public.automation_rules (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  name text,
  description text,
  is_active boolean DEFAULT false,
  trigger_entity text,
  trigger_event text,
  trigger_conditions text,
  actions text,
  cron_expression text,
  run_count numeric,
  max_runs numeric,
  last_run_at timestamptz,
  next_run_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  deleted_at timestamptz,
  created_by uuid REFERENCES auth.users(id)
);

ALTER TABLE public.automation_rules ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "org_isolation" ON public.automation_rules;
CREATE POLICY "org_isolation" ON public.automation_rules
  FOR ALL USING (organization_id = (SELECT organization_id FROM public.organization_members WHERE user_id = auth.uid() LIMIT 1));

CREATE TABLE IF NOT EXISTS public.bank_connections (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  institution_name text,
  account_name text,
  account_mask text,
  account_type text,
  provider text,
  status text,
  last_sync_at timestamptz,
  last_sync_error text,
  bank_account_id uuid,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  deleted_at timestamptz,
  created_by uuid REFERENCES auth.users(id)
);

ALTER TABLE public.bank_connections ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "org_isolation" ON public.bank_connections;
CREATE POLICY "org_isolation" ON public.bank_connections
  FOR ALL USING (organization_id = (SELECT organization_id FROM public.organization_members WHERE user_id = auth.uid() LIMIT 1));

CREATE TABLE IF NOT EXISTS public.budget_phases (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  budget_id uuid,
  name text,
  description text,
  phase_order numeric,
  production_phase text,
  start_date date,
  end_date date,
  planned_amount numeric(12,2),
  actual_amount numeric(12,2),
  status text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  deleted_at timestamptz,
  created_by uuid REFERENCES auth.users(id)
);

ALTER TABLE public.budget_phases ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "org_isolation" ON public.budget_phases;
CREATE POLICY "org_isolation" ON public.budget_phases
  FOR ALL USING (organization_id = (SELECT organization_id FROM public.organization_members WHERE user_id = auth.uid() LIMIT 1));

CREATE TABLE IF NOT EXISTS public.budget_templates (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  name text,
  description text,
  budget_type text,
  production_type text,
  is_default boolean DEFAULT false,
  template_data jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  deleted_at timestamptz,
  created_by uuid REFERENCES auth.users(id)
);

ALTER TABLE public.budget_templates ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "org_isolation" ON public.budget_templates;
CREATE POLICY "org_isolation" ON public.budget_templates
  FOR ALL USING (organization_id = (SELECT organization_id FROM public.organization_members WHERE user_id = auth.uid() LIMIT 1));

CREATE TABLE IF NOT EXISTS public.challenge_participants (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  challenge_id uuid,
  user_id uuid,
  status text,
  progress_percent numeric,
  score numeric,
  rank numeric,
  joined_at timestamptz,
  completed_at timestamptz,
  last_activity_at timestamptz,
  team_id uuid,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  deleted_at timestamptz,
  created_by uuid REFERENCES auth.users(id)
);

ALTER TABLE public.challenge_participants ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "org_isolation" ON public.challenge_participants;
CREATE POLICY "org_isolation" ON public.challenge_participants
  FOR ALL USING (organization_id = (SELECT organization_id FROM public.organization_members WHERE user_id = auth.uid() LIMIT 1));

CREATE TABLE IF NOT EXISTS public.client_portal_access (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  company_id uuid,
  contact_id uuid,
  is_active boolean DEFAULT false,
  access_level text,
  last_login_at timestamptz,
  login_count numeric,
  can_view_budgets boolean DEFAULT false,
  can_view_invoices boolean DEFAULT false,
  can_view_tasks boolean DEFAULT false,
  can_view_documents boolean DEFAULT false,
  can_view_reports boolean DEFAULT false,
  can_comment boolean DEFAULT false,
  can_approve boolean DEFAULT false,
  can_upload boolean DEFAULT false,
  custom_welcome_message text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  deleted_at timestamptz,
  created_by uuid REFERENCES auth.users(id)
);

ALTER TABLE public.client_portal_access ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "org_isolation" ON public.client_portal_access;
CREATE POLICY "org_isolation" ON public.client_portal_access
  FOR ALL USING (organization_id = (SELECT organization_id FROM public.organization_members WHERE user_id = auth.uid() LIMIT 1));

CREATE TABLE IF NOT EXISTS public.clock_entries (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  employee_id uuid,
  clock_in timestamptz,
  clock_out timestamptz,
  clock_in_location text,
  clock_out_location text,
  clock_in_lat numeric,
  clock_in_lng numeric,
  clock_out_lat numeric,
  clock_out_lng numeric,
  total_hours numeric,
  break_minutes numeric,
  status text,
  notes text,
  shift_id uuid,
  approved_by_id uuid,
  approved_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  deleted_at timestamptz,
  created_by uuid REFERENCES auth.users(id)
);

ALTER TABLE public.clock_entries ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "org_isolation" ON public.clock_entries;
CREATE POLICY "org_isolation" ON public.clock_entries
  FOR ALL USING (organization_id = (SELECT organization_id FROM public.organization_members WHERE user_id = auth.uid() LIMIT 1));

CREATE TABLE IF NOT EXISTS public.conversations (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  type text,
  name text,
  participant_ids jsonb,
  last_message_at timestamptz,
  last_message_preview text,
  unread_count numeric,
  is_muted boolean DEFAULT false,
  is_archived boolean DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  deleted_at timestamptz,
  created_by uuid REFERENCES auth.users(id)
);

ALTER TABLE public.conversations ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "org_isolation" ON public.conversations;
CREATE POLICY "org_isolation" ON public.conversations
  FOR ALL USING (organization_id = (SELECT organization_id FROM public.organization_members WHERE user_id = auth.uid() LIMIT 1));

CREATE TABLE IF NOT EXISTS public.credit_notes (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  credit_note_number text,
  invoice_id uuid,
  customer_id uuid,
  issue_date date,
  amount numeric(12,2),
  reason text,
  status text,
  description text,
  applied_date date,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  deleted_at timestamptz,
  created_by uuid REFERENCES auth.users(id)
);

ALTER TABLE public.credit_notes ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "org_isolation" ON public.credit_notes;
CREATE POLICY "org_isolation" ON public.credit_notes
  FOR ALL USING (organization_id = (SELECT organization_id FROM public.organization_members WHERE user_id = auth.uid() LIMIT 1));

CREATE TABLE IF NOT EXISTS public.crew_checkins (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  crew_member_id uuid,
  event_id uuid,
  shift_id uuid,
  department_id uuid,
  role text,
  status text,
  check_in_time timestamptz,
  check_out_time timestamptz,
  scheduled_start timestamptz,
  scheduled_end timestamptz,
  check_in_method text,
  check_in_location jsonb,
  check_out_location jsonb,
  geofence_valid boolean DEFAULT false,
  break_start timestamptz,
  break_end timestamptz,
  total_break_minutes numeric,
  notes text,
  verified_by_id uuid,
  photo_url text,
  device_id text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  deleted_at timestamptz,
  created_by uuid REFERENCES auth.users(id)
);

ALTER TABLE public.crew_checkins ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "org_isolation" ON public.crew_checkins;
CREATE POLICY "org_isolation" ON public.crew_checkins
  FOR ALL USING (organization_id = (SELECT organization_id FROM public.organization_members WHERE user_id = auth.uid() LIMIT 1));

CREATE TABLE IF NOT EXISTS public.crew_gig_ratings (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  employee_id uuid,
  project_id uuid,
  overall_rating numeric,
  professionalism_rating numeric,
  skill_rating numeric,
  reliability_rating numeric,
  communication_rating numeric,
  teamwork_rating numeric,
  role_during_project text,
  would_rehire boolean DEFAULT false,
  comments text,
  is_private boolean DEFAULT false,
  rated_by uuid,
  rated_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  deleted_at timestamptz,
  created_by uuid REFERENCES auth.users(id)
);

ALTER TABLE public.crew_gig_ratings ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "org_isolation" ON public.crew_gig_ratings;
CREATE POLICY "org_isolation" ON public.crew_gig_ratings
  FOR ALL USING (organization_id = (SELECT organization_id FROM public.organization_members WHERE user_id = auth.uid() LIMIT 1));

CREATE TABLE IF NOT EXISTS public.document_templates (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  name text,
  description text,
  category text,
  content text,
  variables jsonb,
  is_active boolean DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  deleted_at timestamptz,
  created_by uuid REFERENCES auth.users(id)
);

ALTER TABLE public.document_templates ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "org_isolation" ON public.document_templates;
CREATE POLICY "org_isolation" ON public.document_templates
  FOR ALL USING (organization_id = (SELECT organization_id FROM public.organization_members WHERE user_id = auth.uid() LIMIT 1));

CREATE TABLE IF NOT EXISTS public.equipment_tracking (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  asset_id uuid,
  event_id uuid,
  barcode text,
  rfid_tag text,
  status text,
  condition text,
  current_location text,
  location_coordinates jsonb,
  zone_id uuid,
  assigned_to_id uuid,
  checked_out_by_id uuid,
  checked_out_at timestamptz,
  expected_return_at timestamptz,
  returned_at timestamptz,
  last_scanned_at timestamptz,
  last_scanned_by_id uuid,
  scan_count numeric,
  notes text,
  damage_report text,
  photos text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  deleted_at timestamptz,
  created_by uuid REFERENCES auth.users(id)
);

ALTER TABLE public.equipment_tracking ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "org_isolation" ON public.equipment_tracking;
CREATE POLICY "org_isolation" ON public.equipment_tracking
  FOR ALL USING (organization_id = (SELECT organization_id FROM public.organization_members WHERE user_id = auth.uid() LIMIT 1));

CREATE TABLE IF NOT EXISTS public.escalation_chains (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  name text,
  description text,
  incident_type text,
  min_severity text,
  is_active boolean DEFAULT false,
  event_id uuid,
  venue_id uuid,
  steps jsonb,
  notification_channels jsonb,
  auto_escalate boolean DEFAULT false,
  created_by_id uuid,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  deleted_at timestamptz,
  created_by uuid REFERENCES auth.users(id)
);

ALTER TABLE public.escalation_chains ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "org_isolation" ON public.escalation_chains;
CREATE POLICY "org_isolation" ON public.escalation_chains
  FOR ALL USING (organization_id = (SELECT organization_id FROM public.organization_members WHERE user_id = auth.uid() LIMIT 1));

CREATE TABLE IF NOT EXISTS public.expense_approval_policies (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  name text,
  description text,
  min_amount numeric(12,2),
  max_amount numeric(12,2),
  auto_approve_below numeric(12,2),
  approval_levels numeric,
  requires_receipt boolean DEFAULT false,
  is_active boolean DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  deleted_at timestamptz,
  created_by uuid REFERENCES auth.users(id)
);

ALTER TABLE public.expense_approval_policies ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "org_isolation" ON public.expense_approval_policies;
CREATE POLICY "org_isolation" ON public.expense_approval_policies
  FOR ALL USING (organization_id = (SELECT organization_id FROM public.organization_members WHERE user_id = auth.uid() LIMIT 1));

CREATE TABLE IF NOT EXISTS public.inbox (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  type text,
  title text,
  body text,
  source_entity text,
  source_id text,
  status text,
  priority text,
  due_at timestamptz,
  actioned_at timestamptz,
  action_type text,
  from_user_id uuid,
  user_id uuid,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  deleted_at timestamptz,
  created_by uuid REFERENCES auth.users(id)
);

ALTER TABLE public.inbox ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "org_isolation" ON public.inbox;
CREATE POLICY "org_isolation" ON public.inbox
  FOR ALL USING (organization_id = (SELECT organization_id FROM public.organization_members WHERE user_id = auth.uid() LIMIT 1));

CREATE TABLE IF NOT EXISTS public.labor_rule_sets (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  name text,
  description text,
  rule_type text,
  jurisdiction text,
  is_default boolean DEFAULT false,
  is_active boolean DEFAULT false,
  standard_daily_hours numeric,
  standard_weekly_hours numeric,
  overtime_after_daily_hours numeric,
  overtime_multiplier numeric,
  double_time_after_daily_hours numeric,
  double_time_multiplier numeric,
  golden_time_after_daily_hours numeric,
  golden_time_multiplier numeric,
  meal_break_required_after_hours numeric,
  meal_break_duration_minutes numeric,
  meal_penalty_amount numeric(12,2),
  minimum_turnaround_hours numeric,
  turnaround_violation_multiplier numeric,
  saturday_multiplier numeric,
  sunday_multiplier numeric,
  holiday_multiplier numeric,
  minimum_call_hours numeric,
  per_diem_amount numeric(12,2),
  effective_date date,
  expiration_date date,
  notes text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  deleted_at timestamptz,
  created_by uuid REFERENCES auth.users(id)
);

ALTER TABLE public.labor_rule_sets ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "org_isolation" ON public.labor_rule_sets;
CREATE POLICY "org_isolation" ON public.labor_rule_sets
  FOR ALL USING (organization_id = (SELECT organization_id FROM public.organization_members WHERE user_id = auth.uid() LIMIT 1));

CREATE TABLE IF NOT EXISTS public.meeting_types (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  name text,
  slug text,
  description text,
  duration_minutes text,
  location_type text,
  video_provider text,
  buffer_before_minutes numeric,
  buffer_after_minutes numeric,
  min_notice_hours numeric,
  max_days_ahead numeric,
  requires_confirmation boolean DEFAULT false,
  color text,
  is_active boolean DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  deleted_at timestamptz,
  created_by uuid REFERENCES auth.users(id)
);

ALTER TABLE public.meeting_types ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "org_isolation" ON public.meeting_types;
CREATE POLICY "org_isolation" ON public.meeting_types
  FOR ALL USING (organization_id = (SELECT organization_id FROM public.organization_members WHERE user_id = auth.uid() LIMIT 1));

CREATE TABLE IF NOT EXISTS public.meetings (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  guest_name text,
  guest_email text,
  guest_phone text,
  meeting_type_id uuid,
  starts_at timestamptz,
  ends_at timestamptz,
  status text,
  location_type text,
  video_link text,
  contact_id uuid,
  company_id uuid,
  deal_id uuid,
  host_notes text,
  cancellation_reason text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  deleted_at timestamptz,
  created_by uuid REFERENCES auth.users(id)
);

ALTER TABLE public.meetings ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "org_isolation" ON public.meetings;
CREATE POLICY "org_isolation" ON public.meetings
  FOR ALL USING (organization_id = (SELECT organization_id FROM public.organization_members WHERE user_id = auth.uid() LIMIT 1));

CREATE TABLE IF NOT EXISTS public.packing_lists (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  packing_list_number text,
  shipment_id uuid,
  event_id uuid,
  status text,
  total_items numeric,
  packed_items numeric,
  packed_by uuid,
  verified_by uuid,
  packed_at timestamptz,
  verified_at timestamptz,
  notes text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  deleted_at timestamptz,
  created_by uuid REFERENCES auth.users(id)
);

ALTER TABLE public.packing_lists ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "org_isolation" ON public.packing_lists;
CREATE POLICY "org_isolation" ON public.packing_lists
  FOR ALL USING (organization_id = (SELECT organization_id FROM public.organization_members WHERE user_id = auth.uid() LIMIT 1));

CREATE TABLE IF NOT EXISTS public.pay_stubs (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  payroll_run_id uuid,
  employee_id uuid,
  gross_pay numeric(12,2),
  total_deductions numeric(12,2),
  net_pay numeric(12,2),
  regular_hours numeric,
  overtime_hours numeric,
  pay_date date,
  status text,
  notes text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  deleted_at timestamptz,
  created_by uuid REFERENCES auth.users(id)
);

ALTER TABLE public.pay_stubs ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "org_isolation" ON public.pay_stubs;
CREATE POLICY "org_isolation" ON public.pay_stubs
  FOR ALL USING (organization_id = (SELECT organization_id FROM public.organization_members WHERE user_id = auth.uid() LIMIT 1));

CREATE TABLE IF NOT EXISTS public.payment_milestones (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  budget_id uuid,
  name text,
  description text,
  milestone_order numeric,
  percentage numeric,
  fixed_amount numeric(12,2),
  trigger_type text,
  trigger_date date,
  trigger_phase text,
  due_date date,
  status text,
  invoice_id uuid,
  paid_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  deleted_at timestamptz,
  created_by uuid REFERENCES auth.users(id)
);

ALTER TABLE public.payment_milestones ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "org_isolation" ON public.payment_milestones;
CREATE POLICY "org_isolation" ON public.payment_milestones
  FOR ALL USING (organization_id = (SELECT organization_id FROM public.organization_members WHERE user_id = auth.uid() LIMIT 1));

CREATE TABLE IF NOT EXISTS public.payroll_deductions (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  name text,
  deduction_type text,
  calculation_method text,
  rate numeric,
  fixed_amount numeric(12,2),
  is_pre_tax boolean DEFAULT false,
  is_employer_match boolean DEFAULT false,
  is_active boolean DEFAULT false,
  notes text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  deleted_at timestamptz,
  created_by uuid REFERENCES auth.users(id)
);

ALTER TABLE public.payroll_deductions ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "org_isolation" ON public.payroll_deductions;
CREATE POLICY "org_isolation" ON public.payroll_deductions
  FOR ALL USING (organization_id = (SELECT organization_id FROM public.organization_members WHERE user_id = auth.uid() LIMIT 1));

CREATE TABLE IF NOT EXISTS public.payroll_rates (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  employee_id uuid,
  rate_type text,
  base_rate numeric(12,2),
  overtime_rate numeric(12,2),
  double_time_rate numeric(12,2),
  effective_date date,
  end_date date,
  department text,
  is_active boolean DEFAULT false,
  notes text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  deleted_at timestamptz,
  created_by uuid REFERENCES auth.users(id)
);

ALTER TABLE public.payroll_rates ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "org_isolation" ON public.payroll_rates;
CREATE POLICY "org_isolation" ON public.payroll_rates
  FOR ALL USING (organization_id = (SELECT organization_id FROM public.organization_members WHERE user_id = auth.uid() LIMIT 1));

CREATE TABLE IF NOT EXISTS public.price_lists (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  name text,
  description text,
  currency text,
  effective_date date,
  expiration_date date,
  is_default boolean DEFAULT false,
  is_active boolean DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  deleted_at timestamptz,
  created_by uuid REFERENCES auth.users(id)
);

ALTER TABLE public.price_lists ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "org_isolation" ON public.price_lists;
CREATE POLICY "org_isolation" ON public.price_lists
  FOR ALL USING (organization_id = (SELECT organization_id FROM public.organization_members WHERE user_id = auth.uid() LIMIT 1));

CREATE TABLE IF NOT EXISTS public.products (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  name text,
  product_type text,
  sku text,
  description text,
  category text,
  unit_price numeric(12,2),
  unit text,
  cost numeric(12,2),
  tax_rate numeric,
  status text,
  is_taxable boolean DEFAULT false,
  notes text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  deleted_at timestamptz,
  created_by uuid REFERENCES auth.users(id)
);

ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "org_isolation" ON public.products;
CREATE POLICY "org_isolation" ON public.products
  FOR ALL USING (organization_id = (SELECT organization_id FROM public.organization_members WHERE user_id = auth.uid() LIMIT 1));

CREATE TABLE IF NOT EXISTS public.project_post_mortems (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  project_id uuid,
  title text,
  status text,
  meeting_date date,
  facilitator_id uuid,
  summary text,
  what_went_well text,
  what_went_wrong text,
  what_to_improve text,
  action_items jsonb,
  budget_variance_pct numeric,
  schedule_variance_days numeric,
  client_satisfaction_score numeric,
  team_satisfaction_score numeric,
  safety_incidents numeric,
  tags text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  deleted_at timestamptz,
  created_by uuid REFERENCES auth.users(id)
);

ALTER TABLE public.project_post_mortems ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "org_isolation" ON public.project_post_mortems;
CREATE POLICY "org_isolation" ON public.project_post_mortems
  FOR ALL USING (organization_id = (SELECT organization_id FROM public.organization_members WHERE user_id = auth.uid() LIMIT 1));

CREATE TABLE IF NOT EXISTS public.project_templates (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  name text,
  description text,
  production_type text,
  category text,
  icon text,
  color text,
  default_status text,
  default_visibility text,
  default_priority text,
  estimated_duration_days numeric,
  budget_template_id uuid,
  usage_count numeric,
  is_active boolean DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  deleted_at timestamptz,
  created_by uuid REFERENCES auth.users(id)
);

ALTER TABLE public.project_templates ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "org_isolation" ON public.project_templates;
CREATE POLICY "org_isolation" ON public.project_templates
  FOR ALL USING (organization_id = (SELECT organization_id FROM public.organization_members WHERE user_id = auth.uid() LIMIT 1));

CREATE TABLE IF NOT EXISTS public.punch_lists (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  title text,
  description text,
  event_id uuid,
  venue_id uuid,
  location text,
  priority text,
  status text,
  assigned_to uuid,
  due_date date,
  resolved_at timestamptz,
  photos text,
  notes text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  deleted_at timestamptz,
  created_by uuid REFERENCES auth.users(id)
);

ALTER TABLE public.punch_lists ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "org_isolation" ON public.punch_lists;
CREATE POLICY "org_isolation" ON public.punch_lists
  FOR ALL USING (organization_id = (SELECT organization_id FROM public.organization_members WHERE user_id = auth.uid() LIMIT 1));

CREATE TABLE IF NOT EXISTS public.quotes (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  quote_number text,
  title text,
  client_id uuid,
  contact_id uuid,
  project_id uuid,
  event_id uuid,
  status text,
  valid_until date,
  subtotal numeric(12,2),
  tax_rate numeric,
  tax_amount numeric(12,2),
  discount_amount numeric(12,2),
  total_amount numeric(12,2),
  currency text,
  payment_terms numeric,
  terms_and_conditions text,
  notes text,
  internal_notes text,
  sent_at timestamptz,
  viewed_at timestamptz,
  accepted_at timestamptz,
  declined_at timestamptz,
  decline_reason text,
  converted_invoice_id uuid,
  converted_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  deleted_at timestamptz,
  created_by uuid REFERENCES auth.users(id)
);

ALTER TABLE public.quotes ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "org_isolation" ON public.quotes;
CREATE POLICY "org_isolation" ON public.quotes
  FOR ALL USING (organization_id = (SELECT organization_id FROM public.organization_members WHERE user_id = auth.uid() LIMIT 1));

CREATE TABLE IF NOT EXISTS public.reactions (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  user_id uuid,
  target_type text,
  target_id text,
  emoji text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  deleted_at timestamptz,
  created_by uuid REFERENCES auth.users(id)
);

ALTER TABLE public.reactions ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "org_isolation" ON public.reactions;
CREATE POLICY "org_isolation" ON public.reactions
  FOR ALL USING (organization_id = (SELECT organization_id FROM public.organization_members WHERE user_id = auth.uid() LIMIT 1));

CREATE TABLE IF NOT EXISTS public.receipt_scans (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  file_name text,
  file_url text,
  status text,
  extracted_vendor text,
  extracted_amount numeric(12,2),
  extracted_date date,
  extracted_category text,
  overall_confidence numeric,
  expense_id uuid,
  error_message text,
  ocr_provider text,
  processing_time_ms numeric,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  deleted_at timestamptz,
  created_by uuid REFERENCES auth.users(id)
);

ALTER TABLE public.receipt_scans ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "org_isolation" ON public.receipt_scans;
CREATE POLICY "org_isolation" ON public.receipt_scans
  FOR ALL USING (organization_id = (SELECT organization_id FROM public.organization_members WHERE user_id = auth.uid() LIMIT 1));

CREATE TABLE IF NOT EXISTS public.reminder_templates (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  name text,
  trigger_type text,
  trigger_days numeric,
  subject text,
  body text,
  is_active boolean DEFAULT false,
  is_default boolean DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  deleted_at timestamptz,
  created_by uuid REFERENCES auth.users(id)
);

ALTER TABLE public.reminder_templates ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "org_isolation" ON public.reminder_templates;
CREATE POLICY "org_isolation" ON public.reminder_templates
  FOR ALL USING (organization_id = (SELECT organization_id FROM public.organization_members WHERE user_id = auth.uid() LIMIT 1));

CREATE TABLE IF NOT EXISTS public.rfp_responses (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  rfp_number text,
  title text,
  deal_id uuid,
  issuing_organization text,
  status text,
  received_date date,
  due_date date,
  submission_date date,
  proposed_amount numeric(12,2),
  proposed_timeline text,
  key_differentiators text,
  team_lead_id uuid,
  response_document_id uuid,
  outcome_notes text,
  feedback_received text,
  tags text,
  notes text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  deleted_at timestamptz,
  created_by uuid REFERENCES auth.users(id)
);

ALTER TABLE public.rfp_responses ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "org_isolation" ON public.rfp_responses;
CREATE POLICY "org_isolation" ON public.rfp_responses
  FOR ALL USING (organization_id = (SELECT organization_id FROM public.organization_members WHERE user_id = auth.uid() LIMIT 1));

CREATE TABLE IF NOT EXISTS public.shift_swap_requests (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  original_shift_id uuid,
  requesting_employee_id uuid,
  target_employee_id uuid,
  swap_type text,
  status text,
  reason text,
  requester_notes text,
  target_notes text,
  manager_notes text,
  requested_at timestamptz,
  expires_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  deleted_at timestamptz,
  created_by uuid REFERENCES auth.users(id)
);

ALTER TABLE public.shift_swap_requests ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "org_isolation" ON public.shift_swap_requests;
CREATE POLICY "org_isolation" ON public.shift_swap_requests
  FOR ALL USING (organization_id = (SELECT organization_id FROM public.organization_members WHERE user_id = auth.uid() LIMIT 1));

CREATE TABLE IF NOT EXISTS public.storage_bins (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  name text,
  code text,
  warehouse_id uuid,
  zone text,
  aisle text,
  rack text,
  shelf text,
  bin_type text,
  capacity numeric,
  current_count numeric,
  is_active boolean DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  deleted_at timestamptz,
  created_by uuid REFERENCES auth.users(id)
);

ALTER TABLE public.storage_bins ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "org_isolation" ON public.storage_bins;
CREATE POLICY "org_isolation" ON public.storage_bins
  FOR ALL USING (organization_id = (SELECT organization_id FROM public.organization_members WHERE user_id = auth.uid() LIMIT 1));

CREATE TABLE IF NOT EXISTS public.time_punches (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  employee_id uuid,
  punch_type text,
  punch_time timestamptz,
  event_id uuid,
  venue_id uuid,
  is_within_geofence boolean DEFAULT false,
  distance_from_geofence_meters numeric,
  status text,
  photo_url text,
  notes text,
  is_manual_entry boolean DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  deleted_at timestamptz,
  created_by uuid REFERENCES auth.users(id)
);

ALTER TABLE public.time_punches ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "org_isolation" ON public.time_punches;
CREATE POLICY "org_isolation" ON public.time_punches
  FOR ALL USING (organization_id = (SELECT organization_id FROM public.organization_members WHERE user_id = auth.uid() LIMIT 1));

CREATE TABLE IF NOT EXISTS public.timer_sessions (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  user_id uuid,
  project_id uuid,
  task_id uuid,
  event_id uuid,
  description text,
  is_billable boolean DEFAULT false,
  started_at timestamptz,
  stopped_at timestamptz,
  is_running boolean DEFAULT false,
  accumulated_seconds numeric,
  time_entry_id uuid,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  deleted_at timestamptz,
  created_by uuid REFERENCES auth.users(id)
);

ALTER TABLE public.timer_sessions ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "org_isolation" ON public.timer_sessions;
CREATE POLICY "org_isolation" ON public.timer_sessions
  FOR ALL USING (organization_id = (SELECT organization_id FROM public.organization_members WHERE user_id = auth.uid() LIMIT 1));

CREATE TABLE IF NOT EXISTS public.user_follows (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  follower_id uuid,
  following_id text,
  following_type text,
  notify_on_update boolean DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  deleted_at timestamptz,
  created_by uuid REFERENCES auth.users(id)
);

ALTER TABLE public.user_follows ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "org_isolation" ON public.user_follows;
CREATE POLICY "org_isolation" ON public.user_follows
  FOR ALL USING (organization_id = (SELECT organization_id FROM public.organization_members WHERE user_id = auth.uid() LIMIT 1));

CREATE TABLE IF NOT EXISTS public.user_points (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  user_id uuid,
  points numeric,
  lifetime_points numeric,
  level numeric,
  level_progress numeric,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  deleted_at timestamptz,
  created_by uuid REFERENCES auth.users(id)
);

ALTER TABLE public.user_points ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "org_isolation" ON public.user_points;
CREATE POLICY "org_isolation" ON public.user_points
  FOR ALL USING (organization_id = (SELECT organization_id FROM public.organization_members WHERE user_id = auth.uid() LIMIT 1));

CREATE TABLE IF NOT EXISTS public.vendor_portal_access (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  vendor_id uuid,
  event_id uuid,
  contact_name text,
  contact_email text,
  contact_phone text,
  status text,
  access_level text,
  permissions jsonb,
  access_token text,
  token_expires_at timestamptz,
  last_login_at timestamptz,
  login_count numeric,
  invited_by_id uuid,
  invited_at timestamptz,
  activated_at timestamptz,
  notes text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  deleted_at timestamptz,
  created_by uuid REFERENCES auth.users(id)
);

ALTER TABLE public.vendor_portal_access ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "org_isolation" ON public.vendor_portal_access;
CREATE POLICY "org_isolation" ON public.vendor_portal_access
  FOR ALL USING (organization_id = (SELECT organization_id FROM public.organization_members WHERE user_id = auth.uid() LIMIT 1));

CREATE TABLE IF NOT EXISTS public.warehouse_locations (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  warehouse_id uuid,
  location_code text,
  zone text,
  aisle text,
  rack text,
  shelf text,
  bin text,
  barcode text,
  location_type text,
  capacity_units numeric,
  current_units numeric,
  max_weight_lbs numeric,
  dimensions text,
  is_active boolean DEFAULT false,
  notes text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  deleted_at timestamptz,
  created_by uuid REFERENCES auth.users(id)
);

ALTER TABLE public.warehouse_locations ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "org_isolation" ON public.warehouse_locations;
CREATE POLICY "org_isolation" ON public.warehouse_locations
  FOR ALL USING (organization_id = (SELECT organization_id FROM public.organization_members WHERE user_id = auth.uid() LIMIT 1));

CREATE TABLE IF NOT EXISTS public.weather_alerts (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  title text,
  alert_type text,
  severity text,
  weather_type text,
  event_id uuid,
  venue_id uuid,
  start_time timestamptz,
  end_time timestamptz,
  description text,
  action_taken text,
  status text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  deleted_at timestamptz,
  created_by uuid REFERENCES auth.users(id)
);

ALTER TABLE public.weather_alerts ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "org_isolation" ON public.weather_alerts;
CREATE POLICY "org_isolation" ON public.weather_alerts
  FOR ALL USING (organization_id = (SELECT organization_id FROM public.organization_members WHERE user_id = auth.uid() LIMIT 1));

CREATE TABLE IF NOT EXISTS public.workflow_triggers (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  name text,
  description text,
  trigger_type text,
  workflow_id uuid,
  config jsonb,
  is_active boolean DEFAULT false,
  last_triggered_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  deleted_at timestamptz,
  created_by uuid REFERENCES auth.users(id)
);

ALTER TABLE public.workflow_triggers ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "org_isolation" ON public.workflow_triggers;
CREATE POLICY "org_isolation" ON public.workflow_triggers
  FOR ALL USING (organization_id = (SELECT organization_id FROM public.organization_members WHERE user_id = auth.uid() LIMIT 1));

